### ISSUE TITLE
スクリーンショット左下にプロフィール画像

### ISSUE THREAD

**Issue by hasegaw** [fetus-hina/stat.ink#10]
トップページでスクリーンショットを並べて表示する場合は、
どのプレイヤーの記録が一見わかりづらいので、
プロフィール画像が左下に出るようにしてはどうか。

イメージ

```
　　■■■■■■■■■■■■■■
　　■■■■■■■■■■■■■■
　　■■■■■■■■■■■■■■
　□□□□□■■■■■■■■■■■
　□□□□□■■■■■■■■■■■
　□□□□□

```

**Comment by fetus-hina** [comment]
現状プロフィール画像に相当するものが存在しないのでどうしようかなというところ
（TwitterログインするかMiiを取るとまあそこそこ。あんまりTwitterログインは好きじゃ無い）
とりあえず後回し。

**Comment by fetus-hina** [comment]
refs #15
