### ISSUE TITLE
Navigating pages in short intervals will invalidate the session.

### ISSUE THREAD

**Issue by niyari** [fetus-hina/stat.ink#1008]
バトルの履歴一覧などから、バトルの詳細を見比べるためにいくつかのページを複数のタブで開く動作を行うと、セッションIDの振り直しの影響により、ログアウトされた状態になります。
例えば、2～3ページ/秒で開くと1つのタブがゲスト(ログアウトしている状態)になり、ダブルクリック程度の速度で新たに2つのページを開くと全てのタブでログアウト状態になります。

**Comment by fetus-hina** [comment]
v2.128.2 で直っていると思います。

**Comment by niyari** [comment]
確認しました。対応ありがとうございました。
