### ISSUE TITLE
current X rank powers are not updating 

### ISSUE THREAD

**Issue by Link8451** [fetus-hina/stat.ink#1018]
i am having an issue where my current power statistics are not being updated or updating very slowly current power for tower control should read 2,131.2 but i see 1992.0 
![image](https://user-images.githubusercontent.com/40288663/154369044-9d9b3546-60af-489e-9950-45c753fb7c55.png)
![image](https://user-images.githubusercontent.com/40288663/154369070-172c809f-9dc9-485c-8f8e-2664e8d7d608.png)

**Comment by fetus-hina** [comment]
Thank you for letting me know about the problem.
I confirmed that part of the system is not working properly.
Now executing update-user-stats tasks.

**Comment by fetus-hina** [comment]
Your stats are probably updated.
Please check and let me know updated or not.
If it has been updated, you may or may not close this issue at the same time as your comment.
(Do not close it if not updated)

**Comment by Link8451** [comment]
The issue has been resolved thank you very much
