### ISSUE TITLE
https://stat.ink/ is encountering error 526.

### ISSUE THREAD

**Issue by lin010151** [fetus-hina/stat.ink#1038]
CF shows Invalid SSL certificate. "The origin web server does not have a valid SSL certificate." Cert outdated?

**Comment by fetus-hina** [comment]
Thank you for letting us know.

As you have guessed, [the certificate between our front-end server and CloudFlare has expired](https://twitter.com/fetus_hina/status/1527324737038610432/photo/1) - so you all couldn't access us for about 2 hours.
Sorry for the inconvenience.

**Comment by lin010151** [comment]
ドンマイ！

Your website is great~
Don't mind~
