### ISSUE TITLE
[Enhancement] Properly display battle count

### ISSUE THREAD

**Issue by VGmaster670** [fetus-hina/stat.ink#1060]
Currently, the battle stats page only displays the number of battles uploaded instead of the total battles done, I think it would be better if the page displayed the total number of battles like in the Salmon Run page
![Screenshot 2022-08-13 170408](https://user-images.githubusercontent.com/72361126/184510726-609b653b-f488-4232-8c7a-1aecfcd52e7e.png)

![Screenshot 2022-08-14 142835](https://user-images.githubusercontent.com/72361126/184550144-fe37bae2-acfe-412a-9421-86a8d71e8448.png)

**Comment by niyari** [comment]
Once Splatoon3 is supported, Salmon run counts will also have multiple histories.
stat.ink in users already have a mix of Splatoon1 history and Splatoon2 history.
It would be more useful in the future to correct the counts to the uploaded Salmon run counts.

**Comment by fetus-hina** [comment]
Essentially, Salmon Run is weirder.

Stat.ink does not and will not expect strongly to work with SplatNet.
Users might collect information from SplatNet or analyze screen data, e.g., IkaLog. 
Users might parse the Switch's network traffic, or some might simply prefer to enter the data manually.
Additionally, SplatNet numbers are counted separately for users who have multiple Switch accounts.
