### ISSUE TITLE
[s3] battles order

### ISSUE THREAD

**Issue by paul-sama** [fetus-hina/stat.ink#1085]
battles ordered by upload time desc not the playd time

**Comment by fetus-hina** [comment]
The battles are sorted by the order in which you send them to us. Clients should sort before sending.

**Comment by paul-sama** [comment]
fes battle not support upload now，
when support and upload it will be wrong order

**Comment by frozenpandaman** [comment]
Maybe there could be an option to sort the table on the user page ("splat log")?

I'm also holding off on uploading my post-Splatfest battles because of this.

**Comment by frozenpandaman** [comment]
Are battles always displayed in played order now? Or is there a toggle?
