### ISSUE TITLE
[S3] Make battle filter

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#1093]

**Comment by paul-sama** [comment]
![image](https://user-images.githubusercontent.com/350651/194975668-606756ab-2137-4754-9186-5f2690c65a3e.png)
filter by user id

**Comment by fetus-hina** [comment]
Currently, I have no plan to search by user ID.
And, there are no information that uniquely identifies a user, at least not in the currently registered data.
I may decide to implement it in the future, but even then it will be a mid-stream search.

**Comment by ADeeeee** [comment]
Just a feature request that we could do more about the time filtering like Splatoon2 in order to know how I played during specific time range in "Summary: Based on the current filter".

![image](https://user-images.githubusercontent.com/35981633/206730599-bcf3f65a-dfc5-486c-b7bd-d899712bfeb1.png)
