### ISSUE TITLE
[S3] wrong weapon info

### ISSUE THREAD

**Issue by paul-sama** [fetus-hina/stat.ink#1098]
`Tri-Slosher` sub weapon is `Toxic Mist` not `Splat Bomb`

**Comment by fetus-hina** [comment]
Good catch!

![image](https://user-images.githubusercontent.com/848666/193204199-2f1fc959-85a7-4ad2-ac6f-5c3b1c7de46c.png)
It seems these data have been swapped...

**Comment by fetus-hina** [comment]
They are fixed. Thank you for the report.
