### ISSUE TITLE
[S3] Splatfest (Tri-color Turf War)

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#1107]

**Comment by fetus-hina** [comment]
The team colors (`our_team_color` and `their_team_color`) are available (deployed) now and can use for non-splatfest battles.

**Comment by fetus-hina** [comment]
![image](https://user-images.githubusercontent.com/848666/208263833-e273462f-6470-442c-98b6-141409a4ce17.png)

Limitations (@ first release time): The order of the teams in this table will not be correct.

**Comment by fetus-hina** [comment]
Tricolor Turf War support is deployed :tada::sparkles::tada::sparkles::tada:

The POST API is extended.

- **NOT** related to Tricolor TW
  - `our_team_color`, `their_team_color` are added.
- Tricolor TW
  - The `rule` key `"tricolor"` is added.  This would be used together with `"splatfest_open"`.
  - `third_team_inked`, `third_team_percent` are added. The extension of the existing columns.
  - `third_team_color` is added, of course.
  - `our_team_role`, `their_team_role`, `third_team_role` are added. For role of the teams, `"attacker"` or `"defender"`.
  - `our_team_theme`, `their_team_theme`, `third_team_theme` are added. Localized team name, e.g., `"Rock"`, `"Paper"`, `"Scissors"`.
  - `third_team_players` is added.

Overview for "third team":
- The *submitter*'s (a stat.ink's user's) team is always **`our_team`**.
- The client can choose which of the other two teams will be **`their_team`** and which will be the **`third_team`**.

New type for "color":
- Native type is string (char(8)).
- `rrggbbaa` hexadecimal formatted, like CSS `#rrggbbaa`, but no leading `#`. The value is not case-sensitive.
- `rrggbb` hexadeciamal formatted string is also accepted. In this case, the alpha value is `ff` (non-transparent).
- `"color": {"a": 1.0, "b": 0.454899997, "g": 0.662750006, "r": 0.10588}` will be `1ba974ff` or `1ba974`.

@frozenpandaman @spacemeowx2

**Comment by frozenpandaman** [comment]
So exciting!!! Thanks Hina! And thanks for the heads up!

**Comment by frozenpandaman** [comment]
Will Ultra Signal attempts (`noroshiTry` in SplatNet) be supported on the scoreboard in the future?

**Comment by frozenpandaman** [comment]
Also messaged you directly about this, but uploaded Tricolor Turf War battles are currently giving an Internal Server Error:
https://stat.ink/@frozenpandaman/spl3/4d4cad4f-1021-450f-b5d1-6cc0f251e581

**Comment by spacemeowx2** [comment]
Good job, I will add support as soon as possible

**Comment by fetus-hina** [comment]
> Will Ultra Signal attempts (noroshiTry in SplatNet) be supported on the scoreboard in the future?

Sorry, both `main_struct.signal` and `player_struct.signal` are exist and forgot to document them.

> Tricolor Turf War battles are currently giving an Internal Server Error:

Sorry again, it's fixed.

**Comment by spacemeowx2** [comment]
I found a typo in wiki: there are two `their_team_percent`, maybe one of them is `third`?

**Comment by fetus-hina** [comment]
Yep, I fixed it. It's just a doc error.
