### ISSUE TITLE
It seems that `number` (#1234) may contain alphabetic characters.

### ISSUE THREAD

**Issue by slime-hatena** [fetus-hina/stat.ink#1113]
素晴らしいプロダクトをありがとうございます。プレイの振り返りに活用させていただいております。

#1099 で言及されていたアルファベットを含むナンバーを確認しました。  
以下がs3sで出力したファイルから該当部分を抜き出したものです。  
https://gist.github.com/slime-hatena/248d6b4014dec9265d8a396a15cdd745

実機では以下のバトルメモリーで確認いただけます。  
`RPFT-L16G-VFUT-PAA3`

現状サイト上では空白として記録されています。  
https://stat.ink/@Slime_hatena/spl3/06014c9a-17d5-48e5-865f-958eb6805f01

s3sが実際にこのデータをstat.inkに送信しているかは確認できておりません。  
（まずはs3sに報告すべき事象でしたら申し訳ございません）  
お手すきの際にご確認いただけますと幸いです。よろしくお願いいたします。

![FekntX8aYAAu_E4_orig](https://user-images.githubusercontent.com/11350340/194726846-834dec5b-b029-4b51-9173-79282219af6d.jpg)

**Comment by fetus-hina** [comment]
#1099

**Comment by fetus-hina** [comment]
ありがとうございます。
#1099 でレポートされている内容ですが、実際のデータが確認できていなかったため、
現在は「とりあえず数字以外を含んでいれば受け取っていないかのようにふるまう」ようにしています。
（なので、ご指摘の内容は完全に stat.ink の挙動です）

実機で表示が確認できましたので、ご報告内容をもとに、文字列を受け入れるように変更します。

**Comment by fetus-hina** [comment]
パラメータおよびDBの型変更が完了しました。
新しい投稿データは `1734b` のような文字列をそのまま記録します。

既に投稿されているデータ（例えば [06014c9a-17d5-48e5-865f-958eb6805f01](https://stat.ink/@Slime_hatena/spl3/06014c9a-17d5-48e5-865f-958eb6805f01)）は、
stat.ink投稿時にデータが失われているため何もできません。

この `#id` はほとんどの場合欠損しても特に問題がないデータだと思いますが、
どうしても必要であれば、 [簡易削除ツール](https://github.com/frozenpandaman/s3s/issues/29#issuecomment-1259536513) を使うなどして対応をお願いします。
(`shas` に削除するバトルの UUID を並べるとおそらく動きます)
