### ISSUE TITLE
[i18n] Different phrases between simplified and traditional Chinese

### ISSUE THREAD

**Issue by Victrid** [fetus-hina/stat.ink#1116]
Hello,

I've seen a translation modification from recent commit:

```diff
diff --git a/messages/zh-CN/alert.php b/messages/zh-CN/alert.php
index 944f20e6..b45997c6 100644
--- a/messages/zh-CN/alert.php
+++ b/messages/zh-CN/alert.php
@@ -17,5 +17,5 @@ return [
     'Term: {startDate} - {endDate}' => '时间：{startDate} - {endDate}',
     'We\'ll perform maintenance on the schedule below:' => '我们会在以下时间进行伺服器维护：',
     'We won\'t implement automatic importing to {appName} for security reasons.' => '出于资安考量，我们不支援使用 {appName} 来自动汇入。',
-    'You can import automatically from SplatNet, use these apps: (USE AT YOUR OWN RISK)' => '你可以使用这些应用来从SplatNet自动汇入资料(风险自负)',
+    'You can import automatically from SplatNet, use these apps: (USE AT YOUR OWN RISK)' => '你可以使用这些软体来从SplatNet自动汇入资料(风险自负)',
 ];
diff --git a/messages/zh-TW/alert.php b/messages/zh-TW/alert.php
index cc93b0ff..f79897ba 100644
--- a/messages/zh-TW/alert.php
+++ b/messages/zh-TW/alert.php
@@ -18,5 +18,5 @@ return [
     'Term: {startDate} - {endDate}' => '時間：{startDate} - {endDate}',
     'We\'ll perform maintenance on the schedule below:' => '我們會在以下時間進行伺服器維護：',
     'We won\'t implement automatic importing to {appName} for security reasons.' => '出於資安考量，我們不支援使用 {appName} 來自動匯入。',
-    'You can import automatically from SplatNet, use these apps: (USE AT YOUR OWN RISK)' => '你可以使用這些應用來從SplatNet自動匯入資料(風險自負)',
+    'You can import automatically from SplatNet, use these apps: (USE AT YOUR OWN RISK)' => '你可以使用這些軟體來從SplatNet自動匯入資料(風險自負)',
 ];
```

This commit modified zh-TW's `應用` to `軟體`, meanwhile also modified zh-CN's `应用` to `软体`. 

Due to historical reasons, those two language variants differs especially in IT related phrases. 

`應用` as application, can be used in both zh-CN and zh-TW, but `軟體` as software is only applicable to zh-TW, while in zh-CN this means animals like squids which don't have a bone (軟体動物門に分類される動物の総称).

`伺服器` in zh-TW would be equivalent to `服务器` in zh-CN, where `伺服` means `servo` （サーボ機構） and is exclusively used in things like `伺服电机` (servo motors, サーボモータ).

Here are a list that zh-CN would be different with zh-TW in `messages/zh-CN/alert.php`:

| English | Smpl. Chinese (esp. zh-CN) | Trad. Chinese (esp. zh-TW) |
| :--: | :--: | :--: |
| app, application | 应用，应用软件 | 應用，應用軟體 |
| software | 软件 | 軟體 |
| (server) maintenance | （服务器）维护 | （伺服器）維護 |
| (information) security | （信息）安全 | 資安 |
| support | 支持 | 支援 |

Translators like Google Translator cannot see the difference in Chinese smpl. to Chinese trad. correctly. 

I can fix these with a pull request if you need them.

**Comment by fetus-hina** [comment]
Thank you the information. I'll revert it for Traditional Chinese.

**Comment by fetus-hina** [comment]
I'm not sure what the final result will be, so please create a pull request for me to help out.
Then I will not do any automatic conversion using OpenCC in the future.

**Comment by Victrid** [comment]
Well, OpenCC could be the best converter now, but doing this would be a Sisyphean task :crying_cat_face:

**Comment by ADeeeee** [comment]
It's okay for doing the automatic conversion with OpenCC if there's no translation. We could just correct it manually then. Although it's not the fluent one we used daily, we could still understand what it's talking about.

I'm correcting them in my commit in zh-TW, but still welcome for having a PR instead of missing it.

**Comment by fetus-hina** [comment]
Close this issue.
Please create a Pull Request if necessary.
