### ISSUE TITLE
[s3] query battle by result(judgement)

### ISSUE THREAD

**Issue by paul-sama** [fetus-hina/stat.ink#1122]
is there a way query battle by battle["judgement"], need know the count of `DRAW`, `DEEMED_LOSE`

I get a `res['data']['playHistory']['battleNumTotal']` from SplatNet `29957cf5d57b893934de857317cd46d8` 
total 800
from stat.ink get total 838, missing a Tricolor battle which total 839.

compare all battle saved in my local db,
get 

 4,EXEMPTED_LOSE
13,DRAW
26,DEEMED_LOSE
339,LOSE
457,WIN

seem nintendo didn't count `DRAW` and `DEEMED_LOSE` in `battleNumTotal`

and i found s3s didn't post  actual `judgement` until v0.1.5
https://github.com/frozenpandaman/s3s/commit/8d760561430552877a60b9c8d294b3f50c536b3a
maybe i need reupload some old battles

**Comment by paul-sama** [comment]
@frozenpandaman  maybe s3s still not post actual `judgement`
```
elif result in ("LOSE", "DEEMED_LOSE"):
		payload["result"] = "lose"
```

**Comment by frozenpandaman** [comment]
stat.ink doesn't support `deemed_lose` as a key, only `lose` and `exempted_lose`:
https://github.com/fetus-hina/stat.ink/wiki/Spl3-API:-Post-v3-battle

for your stats at the top of your page, i think stat.ink doesn't count `deemed_lose` battles (i.e. you disconnected, your k/d is null and stat.ink shows [this](https://user-images.githubusercontent.com/7245874/197973917-2c76c147-924a-4704-a31f-315a6c041882.png)) …maybe `exempted_lose` too? @fetus-hina can confirm
