### ISSUE TITLE
[S3] Salmon Run Next Wave

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#1128]

**Comment by fetus-hina** [comment]
The Salmon Run APIs has been deployed.
Now you can post a job, get UUID list, and delete them by API.
However, there is no page showing them yet.

**Comment by spacemeowx2** [comment]
Hi, I added Salmon Run export support to `s3si.ts`. And I found some issues:

1. Using msgpack will result in an error, while using JSON will not. The server returns:

```json
{
    "error": {
        "waves": "special_uses: Special Uses is invalid. (must be map<string, int>)"
    }
}
```

2. For bosses structure, when I try to use alias (number) as the key of map, the server will report an error:

```json
{
    "error": {
        "bosses": "Bosses is invalid. (must be map<string, struct>)"
    }
}
```

Here is the request:

![image](https://user-images.githubusercontent.com/8019167/202860609-4ff217a4-6d39-43ce-b92f-f08de012dd6c.png)

3. s3si.ts uses name to do the mapping to the key, and therefore relies on the results of https://stat.ink/api/v3/weapon?full=1. However, this JSON is missing `Rare Weapon` on page https://stat.ink/api-info/weapon3. 

Finally, thank you for your work, and welcome to https://github.com/spacemeowx2/s3si.ts/pull/18 for testing and pointing out problems!

**Comment by fetus-hina** [comment]
Integer-like key is too buggy...

**Comment by fetus-hina** [comment]
@spacemeowx2

1. I'm using MessagePack for testing with this data below and it's ok. What message do you sent to the server?
```php
[
    // ...
    'waves' => [
        [
            'tide' => 'normal',
            'event' => null,
            'golden_quota' => 20,
            'golden_delivered' => 21,
            'golden_appearances' => 30,
            'special_uses' => [
                'trizooka' => 1,
                'wave_breaker' => 1,
            ],
        ],
        // ...
    ],
    // ...
];
```

2. maybe fixed by commit ef8f3c952e00941f19d72c222353ed005b8e46c0 .
3. I understand that it is necessary, but I have not gotten around to it due to priorities. And it will be a separate API from the existing one.

**Comment by spacemeowx2** [comment]
@fetus-hina I guess `{"special_uses": {}}` will error.

Here is my request data:

![image](https://user-images.githubusercontent.com/8019167/202870224-9a5344ed-efe7-424a-8c5b-e8ac78462882.png)

Thanks for the fix by the way

**Comment by fetus-hina** [comment]
Note:
```ts
import { encode } from "https://deno.land/x/msgpack@v1.4/mod.ts";
import { hexdump } from "https://deno.land/x/prohazko@1.3.8/hex.ts";

const object = {};
const a: string[] = [];

const encoded1: Uint8Array = encode(object);
const encoded2: Uint8Array = encode(a);

console.log(hexdump(encoded1)); // 80 (hex)
console.log(hexdump(encoded2)); // 90 (hex)
```
from [msgpack spec](https://github.com/msgpack/msgpack/blob/master/spec.md#overview):
0x80: fixmap(0)
0x90: fixarray(0)

decode them by php extension:
```
phponly=0
0x80
array(0) {
}
0x90
array(0) {
}

phponly=1
0x80
object(stdClass)#1 (0) {
}
0x90
array(0) {
}
```

**Comment by fetus-hina** [comment]
Could you try again?
If it still fails, it may be difficult to fix it.

In that case, the following options are available:

1. Set `null` if empty (accepts `{"special_uses": null}`)
2. Set 0-times used data (e.g., `{"special_uses": {"nicedama": 0}}`)
    ---- stat.ink [ignores if value is zero](https://github.com/fetus-hina/stat.ink/blob/d5504b366b4592c55bca4b8f3dcac7d2457343c6/components/validators/SalmonSpecialUse3Validator.php#L92-L95).
4. Add a dummy key with a `null` value. `{"special_uses": {"x": null}}`
    ---- stat.ink [ignores if value is `null` before checking the key](https://github.com/fetus-hina/stat.ink/blob/d5504b366b4592c55bca4b8f3dcac7d2457343c6/components/validators/SalmonSpecialUse3Validator.php#L82-L85)

**Comment by spacemeowx2** [comment]
I tried, and now there are no errors. Good job!

**Comment by fetus-hina** [comment]
@frozenpandaman @spacemeowx2
Salmon Run support is now active. 
Currently the summary at the top of the listing page is not displayed, but it generally works.

**Comment by fetus-hina** [comment]
Close this issue and continue to #1144 and #1145

**Comment by fetus-hina** [comment]
@spacemeowx2 
I added and deployed the `/api/v3/salmon/weapon` API to get weapon list for Salmon Run.
The API will return **full list** of weapons (not only Grizzco weapons) for Salmon Run.
(This API does not return all of weapons. Some weapons are excluded. For example, Hero Shot Replica and Tentatek Splattershot are excluded)
