### ISSUE TITLE
[S3] Allow to edit in detail page to add Live Video Link to each Battle (Youtube or Twitch)

### ISSUE THREAD

**Issue by kenny-wong** [fetus-hina/stat.ink#1130]
Which allow the user to update on each battle detail to add their own youtube link, so as to review the battle by clicking on the link on home page.

The youtube link could be with timestamp started aligned with the battle, but it is manually done by user itself.
Alternatively, user can post the link generated by SP3 upload in Nintendo App.

Question:
How could the "Edit" button be enabled?

Design: 
![image](https://user-images.githubusercontent.com/6819339/201388344-440bb77a-7932-4004-ac83-a7de769817d9.png)

**Comment by fetus-hina** [comment]
Internally, the `link_url` is implement. And, the `link_url` available on the POST API.
In other words, the view to edit the URL is not implemented yet.
This URL can be YouTube or Twitch.

It is a necessary feature, but not set high priority.
We have other important features to implement. For example, Salmon Run and Tri-color Battles.
If details of X-battles and league battles are announced, they will be added to the high-priority task list.


![image](https://user-images.githubusercontent.com/848666/201517159-786ec313-946a-4e39-871b-612f97482347.png)
![image](https://user-images.githubusercontent.com/848666/201517297-75ebea57-4f5d-4ba4-8559-09421228a9f1.png)

**Comment by kenny-wong** [comment]
Hi, 

Thanks for your comment.
Noted with the internal function which have been there.

But how we can update the content of the battle with POST API? (It is currently Creation API only?)
I am using some auto program like s3s to grep the battle from Nintendo and upload, not until I uploaded I dunno the URL of the related battles.

I am willing to update the URL after it is uploaded to stat.ink. Not even with any UI is also fine.

Thanks.

**Comment by kenny-wong** [comment]
X-battles is out, can this added to the high-priority task list?

**Comment by fetus-hina** [comment]
implemented and deployed.
