### ISSUE TITLE
Any way to find the real uploaded splatoon 3 battles's uuid or battle Id?

### ISSUE THREAD

**Issue by Itoktsnhc** [fetus-hina/stat.ink#1133]
My operations:
1. Generate stat ink battle's uuid in [Post battle Api ](https://github.com/fetus-hina/stat.ink/wiki/Spl3-API:-Post-v3-battle)from splatoon battleId(the base64 str)
2. build battle Body and send with battle uuid
3. store the responseBody's uuid

example:
|spl3 raw battleId | statInk's battle body uuid | post battle response's uuid(battleId in Url?)|
| --- | --- | --- |
|VnNIaXN0b3J5RGV0YWlsLXUtYXZzZHRtcXd4emJxZnNmamFubW06QkFOS0FSQToyMDIyMTExNFQxMzQxMjFfNTI5YjZkMjAtYjUzZC00YmJhLWE1NzAtZGMyNDU4MjczNGZi|f2428320-92e5-5c3f-ba26-658b6f6bf0b2|d2a129db-0c89-4983-aa8d-a83ae48b1603|

My questions:
1. Check that if a battle is uploaded before sending the battle detail request to spaltNet（may be slow）, Can I use the **statInk's battle body uuid** to get the **post battle response's uuid** which is not returned in [GetUUIDList Api](https://github.com/fetus-hina/stat.ink/wiki/Spl3-API:-Get-UUID-List-(for-s3s))  ?
2. Can I replace the old (or incorrect) battle data without: 1. get the battleId 2. delete by battleId 3. upload the new one ? Like just set a header in the post request and replace if exist？

Many thanks

**Comment by fetus-hina** [comment]
1. Not available at this time.
2. A post with the same UUID is simply ignored. No overwriting is performed. No `PATCH` method is provided.<br>You must delete it first using the `DELETE` API.

**Comment by Itoktsnhc** [comment]
Thanks , I will store battle Id in response as work around
