### ISSUE TITLE
[s3] peak rank can be different between Series and Open 

### ISSUE THREAD

**Issue by paul-sama** [fetus-hina/stat.ink#1135]
<img width="176" alt="image" src="https://user-images.githubusercontent.com/350651/202755084-36637258-b063-4d88-b1e8-da275fce0ab6.png">

user play Series(Challenge) rank to S+40,
then only play open battles rank to S+46
but now two peak rank always same

**Comment by fetus-hina** [comment]
I have not found any rational reason to consider them separately.
