### ISSUE TITLE
Rank After Exp < 0 may not be error

### ISSUE THREAD

**Issue by tako774** [fetus-hina/stat.ink#1155]
バンカラマッチでウデマエポイントがマイナスになると、以下のエラーが出て報告できません。
クライアントは s3si.ts です。

`error: { rank_after_exp: "Rank After Exp must be no less than 0." }`

ウデマエポイントはマイナスになることがあるので、すくなくとも 0 未満で報告エラーとするチェックは外したほうがいいのかなと思います。

stat.ink いつもお世話になっています。ありがとうございます。

**Comment by fetus-hina** [comment]
この制限を入れていたのをすっかり忘れていました。ありがとうございます。
