### ISSUE TITLE
5 lose for initial X battle

### ISSUE THREAD

**Issue by spacemeowx2** [fetus-hina/stat.ink#1156]
Sadly I just got a 0-5 initial X battle

```json
{
  "xMatchMeasurement": {
      "state": "COMPLETED",
      "xPowerAfter": 1955.8105683835809,
      "isInitial": true,
      "winCount": 0,
      "loseCount": 5,
      "maxInitialBattleCount": 5,
      "maxWinCount": 3,
      "maxLoseCount": 3,
      "vsRule": {
          "name": "真格塔楼",
          "rule": "LOFT",
          "id": "VnNSdWxlLTI="
      }
  }
}
```

And got error: `{ error: { challenge_lose: "Challenge Lose must be no greater than 3." } }`

I think there should be a flag to mark a battle to initial challenge, which allows `challenge_lose` to be 5

**Comment by fetus-hina** [comment]
Stat.ink now accepts 5 wins and 5 loses when lobby is `xmatch`.
Also, to reduce the sense of discomfort, the display method was slightly changed.
