### ISSUE TITLE
Suggestion: sorting keys in `messages/*` to improve translation experience

### ISSUE THREAD

**Issue by cake-monotone** [fetus-hina/stat.ink#1159]
I'm translating the scripts from Japanese to Korean.
There are no big problems, but there is one thing I would like to suggest.

![unordered keys](https://user-images.githubusercontent.com/20366872/205556995-aa178440-d598-4eac-a729-d603b796871e.png)

As you can see, the order of the keys is mixed up, making it difficult to translate one-to-one.
If the keys are sorted, I think I can proceed with the translation more comfortably.

If you are okay, I'll try making PR.

**Comment by fetus-hina** [comment]
Messages are listed in alphabetical order (except Japanese), sorted by PHP's `sort` function.
Japanese messages are arranged in the order in which they are sorted by Vim in my environment.

If necessary, sort both in your environment once using the same procedure.
Then, just commit to the Korean translation and you'll be fine.

**Comment by cake-monotone** [comment]
Do you have no plans to sort and keep Japanese messages in alphabetical order?

It's a minor issue so you can ignore this suggestion.
