### ISSUE TITLE
Salmon Run NW shows poorly on iPad

### ISSUE THREAD

**Issue by spacemeowx2** [fetus-hina/stat.ink#1163]
The first column takes up all the width of the page, while the other columns are stacked on top of each other.

![image](https://user-images.githubusercontent.com/8019167/205842242-7526a7b8-36ab-4985-84bf-b8852d973c9e.png)

![image](https://user-images.githubusercontent.com/8019167/205842437-922c6cde-39a3-45f8-938f-112f497b5824.png)

I found remove these two lines make it work on iPad. Maybe the version of Safari on iPad is too low to support complex calc expressions.

https://github.com/fetus-hina/stat.ink/blob/5560376141ae4e28bc6b908e0151d87acb26839d/resources/stat.ink/salmon-players.scss#L19

https://github.com/fetus-hina/stat.ink/blob/5560376141ae4e28bc6b908e0151d87acb26839d/resources/stat.ink/salmon-waves.scss#L21

I think in a fixed table-layout, the remaining th width should not be necessary (because there is width: 100% on the table).

iPadOS Version: 16.1.1(20B101)

**Comment by fetus-hina** [comment]
I have no Apple devices, so I didn't and couldn't check with them.
However, I think it is a big problem when those devices display so badly.
I'm currently working on a mitigation plan until this is resolved.

**Comment by spacemeowx2** [comment]
I can confirm that it has been fixed, thanks
