### ISSUE TITLE
Incorrect Team Golden Egg Count is Displayed

### ISSUE THREAD

**Issue by VGmaster670** [fetus-hina/stat.ink#1167]
Stat.ink displays 130 eggs when it should be 128
![image](https://user-images.githubusercontent.com/72361126/206824649-bc064cbe-d6e3-4407-b108-c2e11000efcb.png)

![Screenshots_2022-12-09-20-34-03](https://user-images.githubusercontent.com/72361126/206824691-99289be5-37a4-4bbd-a6bf-aa8764808baa.png)

**Comment by fetus-hina** [comment]
(cc: @frozenpandaman, @spacemeowx2)

The number $130$ is calculated in client-side ([s3s source](https://github.com/frozenpandaman/s3s/blob/0ca0e3d1d8fef62debedc2c908eb60e3079762dd/s3s.py#L894-L900), [s3si.ts source](https://github.com/spacemeowx2/s3si.ts/blob/b7ac817014c3630a2bb08f5bfbdeb036ad52c369/src/exporters/stat.ink.ts#L707-L708))
$130=44+37+19+30$
Each number is the "delivery count" for each user and is on your screenshot.

The number $128$ in "Waves" is the total for each wave, calucated by stat.ink.
Perhaps $2(=130-128)$ of these were smoked by the Mothership.

This issue should probably be proposed to s3s.

**Comment by frozenpandaman** [comment]
OMG GITHUB SUPPORTS INLINE LaTeX?!?!?!?!?!?!?

**Comment by frozenpandaman** [comment]
Thanks @VGmaster670 and @fetus-hina! Fixed in s3s v0.2.6 (c9f7808).

**Comment by frozenpandaman** [comment]
@fetus-hina Might it be possible for you to fix these results in the database?

**Comment by fetus-hina** [comment]
- [x] Fix major clients (s3s, s3si.ts)
- [x] Add support for old clients (c31715897f7d366deac62d8a93fe43443f5566af)
- [x] Add data fixer and execute it (74464ab6ab1959e4ef55007e4dc8f90d26f04fb1)

It's done! Thank you for the report.

**Comment by frozenpandaman** [comment]
Actually, note that SplatNet 3 displays these golden egg totals incorrectly too. So, it is a SplatNet bug, but we were sending the data based on that.

**Comment by frozenpandaman** [comment]
I made note of this on my [SplatNet bugs wiki page](https://github.com/frozenpandaman/s3s/wiki/%7C-splatnet-bugs) just in case.
