### ISSUE TITLE
json list of battles for s3

### ISSUE THREAD

**Issue by codl** [fetus-hina/stat.ink#1181]
hi, do you have any plans to add an api for getting a list of a user's battles?

i see for salmon run there is `/@[user]/salmon3.json`, but unfortunately it is limited to the last 100 games, it would be nice to be able to get games between [timestamp] and [timestamp]

but also it would be nice to have something like that for PVP battles

**Comment by TrevorBushnell** [comment]
Would echo that this would be useful, I don't even need that many but being able to go in and pull the last day's worth of battles rather than downloading the entire json file over and over again would be incredibly useful.

**Comment by luiscarlospando** [comment]
Would this be possible in the future?

**Comment by fetus-hina** [comment]
It was added in v3.29.0 (already available!)
It supports specifying page number and applying various filters.

It is convenient to click the "`{}`" icon **after applying the filter** on the user page.

**Comment by luiscarlospando** [comment]
Thanks 🙌, really appreciate it! 🥳
