### ISSUE TITLE
サーモンランのバイトの一覧各ページに意図した件数が表示されていない

### ISSUE THREAD

**Issue by wkoichi** [fetus-hina/stat.ink#1187]
https://stat.ink/@wkoichi/salmon3 でバイトを見たときに、1ページ目の最後と2ページ目の最初に同じバイトが表示されています。バトルや前作のバイトでは、違うバトルやバイトが表示されていますので、意図していない動作だと思います。

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/387175/213951662-b155ef68-4a50-4c1a-a962-efae6e4d21bf.png">
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/387175/213951694-757a69a5-56e1-4069-8e3a-27e3a2620740.png">

**Comment by fetus-hina** [comment]
1ページ目と2ページ目のクエリの差は `OFFSET 100` があるかどうかだけなのに不思議…

**Comment by fetus-hina** [comment]
`salmon_player_weapon3` を `LEFT JOIN` して `LIMIT` をかけているため、同じレコードが複数行吐かれている…

**Comment by fetus-hina** [comment]
上記独り言コメントのように、発行されるSQLに誤りがあったため、そもそも意図した件数が出力されていませんでした。
コミット b5315ab によって修正されたハズです。
