### ISSUE TITLE
Xパワーの数値がイカリング3の表示と一致していない

### ISSUE THREAD

**Issue by wkoichi** [fetus-hina/stat.ink#1189]
stat.inkでは次のマッチのXパワーは 1,922.4 となっていますが、
https://stat.ink/@wkoichi/spl3/48629027-7f6c-4e73-8573-079eb58c0b6c

イカリング3では 1922.3 となっています。
![image](https://user-images.githubusercontent.com/387175/218146797-a0e6042b-b8fe-4fd8-88ec-e8a88d0bbb89.png)

イカリング3のAPIから取得できるXパワーは
`"lastXPower" : 1922.3790670345884`となっており、イカリング3では、 小数第一未満の端数を切り捨てて表示しているようです。

**Comment by fetus-hina** [comment]
v3.36.0 で修正済みですが、データベースには既に 0.1 単位に丸められた（※）数字が記録されていて、元のデータは不明なので、既存のデータについては変更されません。

……まあ X パワーのレーティング偏差が 0.1 単位になることはまずない（＝誤差の範疇）ので気にしないでいいんじゃないですかと思ってます。

※）単に(例えば) `1922.3790670345884` をそのまま `DECIMAL(6, 1)` に格納しようとしているので、具体的な丸めアルゴリズムはわかりません。四捨五入かもしれないし、JIS丸め的な何かかもしれません。

**Comment by wkoichi** [comment]
対応ありがとうございます。
影響はなにもないなとは思いましたが、気づいてしまったのでissuesに登録しました。
