### ISSUE TITLE
Not All Battles Are Captured in stat.ink

### ISSUE THREAD

**Issue by TrevorBushnell** [fetus-hina/stat.ink#1190]
I'm having an issue where the battles being displayed on my public profile is not equal to the number of battles in the json file that I can download from my profile. Currently on stat.ink it says that I have completed 249 battles. However, running the following code to load my json data:

```python
df = pd.DataFrame()
with open("statink-super64guy.json") as f:
    for json_obj in f:
        data = json.loads(json_obj)
        tmp_df = pd.DataFrame.from_dict(data, orient="index").T
        df = pd.concat([df, tmp_df])

print(len(df.index))
battles = list(df['id'])
print(len(set(battles)))
```

I get 349 printed twice, telling me that there are 100 additional battles and every battle is unique. This means that there are just 100 battles missing from the page. Running equivalent code for my salmon run data I find that this is NOT the case (every instance of Salmon Run is captured. Is there a reason for this? It's possible that this was intentional but I couldn't find any explanation for why this was the case, and I would appreciate some reasoning for that!

**Comment by fetus-hina** [comment]
- Tell me your account name (log in name, `@foo` in the URL)
- Did you edit your battles? (Delete, Set/Edit Link URL on the details page)

**Comment by TrevorBushnell** [comment]
That's right! I completely forgot that I deleted my initial 100 battles. My bad! I was messing with settings when I was initially learning the website. Now that this is coming back from the depths of my memory, I'm realizing that I re-uploaded those same battles. So that means that there are 100 duplicate battles in that JSON file on my account. Do you have any tips on what I can do to filter out those duplicate battles? Especially because the code that I ran above tells me that every battle ID is unique even though there are some battles that are in the dataset twice. This would be really important to fix because I don't want duplicate battles in my data analysis.

**Comment by fetus-hina** [comment]
Unfortunately, there is currently no convenient way to do that.
There are several possible implementations.

  - Use [publicly available JSON](https://stat.ink/@super64guy/spl3/index.json)
     (Ref. #1181)
    This way, you can get another "page" by using a method such as `?page=2`.
    You can also refine the acquisition conditions in advance.
    See the issue above to get details.

  - Check duplicates of `start_at`
     When you re-upload the same battle, there should theoretically be a battle with the same `start_at`.
