### ISSUE TITLE
Splatfest Crowns Not Displayed on Stat.ink

### ISSUE THREAD

**Issue by VGmaster670** [fetus-hina/stat.ink#1192]
![image](https://user-images.githubusercontent.com/72361126/218334722-881ce41a-81f8-454d-a98b-2684d9577221.png)
![image](https://user-images.githubusercontent.com/72361126/218334838-0ad6b27e-a800-4365-9140-558a64315908.png)
Stat.ink does not show Splatfest crowns for anyone despite displaying them for X-battles

**Comment by frozenpandaman** [comment]
Would love to see this added too!
