### ISSUE TITLE
Link to sendou.ink's build analyzer

### ISSUE THREAD

**Issue by Itoktsnhc** [fetus-hina/stat.ink#1194]
Recently I am using [sendou.ink's build analyzer](https://sendou.ink/analyzer) for test my build effect, and stat.ink's battle detail page also has a gear ability pop up when click on the player, so is there any chance stat.ink can link to the build analyzer's page?

url sample : `https://sendou.ink/analyzer?weapon=0&build=ISM,ISS,IRU,RSU,SSU,QSJ,SPU,SCU,BRU,RES,BRU,SRU`

query params:
- weapon
- build

**Comment by fetus-hina** [comment]
I deployed the first version.
It can be accessed from the Abilities pop-up.

![image](https://user-images.githubusercontent.com/848666/219365875-353857cf-a63d-49c1-9820-06b84f2baa1d.png)

**Comment by Itoktsnhc** [comment]
Thank you very much!!!
