### ISSUE TITLE
The Titles on Splashtag is not translated

### ISSUE THREAD

**Issue by ADeeeee** [fetus-hina/stat.ink#1196]
Just reporting that it was translated yesterday and now it isn't. 

![image](https://user-images.githubusercontent.com/35981633/219680012-c04fba92-d223-4bff-9819-6dc356bf49a3.png)

**Comment by fetus-hina** [comment]
stat.ink handles only localized strings for SplashTag titles (No re-translation).
In other words, it displays the data as it is sent from the client.
(For example, [my battle](https://stat.ink/@fetus_hina/spl3/528d0471-8e56-45de-9f06-4019b4b7cec5) will remain in Japanese when displayed in any language.)

It would be a locale setting issue in s3s (or other clients).
