### ISSUE TITLE
個人の戦績リストページの改善希望点

### ISSUE THREAD

**Issue by hasegaw** [fetus-hina/stat.ink#12]
Issue 複数にわけると多くなりすぎるのでまとめてひとつのIssueとします。

１）Excel のオートフィルタ風に絞り込み・ソート
````
ルール▼	マップ▼	ブキ▼	結果▼	殺▼	死▼	日時▼
````
　　▼ 部分をクリックすると「昇順」「降順」「（ソートしない）」の選択、
　　特定値の選択が可能なイメージ
　　殺・死・日時は昇順・降順の選択だけでもいいかも

３）テーブルの「死」と「日時」の間に K/D Raito を表示
　　K/D Raito = 殺数 ÷ 死数 を %1.2f ぐらいで 　例（ 3K2D → 1.50 ）
　　1.0 以上なら緑色文字など
　　1.0 イカなら赤色文字などがみやすそう
　　できればソート可能な項目に加えてほしい

４）結果 を色で見分けられるようにする
　　バトル結果ページ同様、結果は緑色・赤色背景とする

５）ブキ絞り込みでは、使ったことのないブキは表示しない
　　もしくは、ブキ選択に使った数を (10) などで出すとか
　　DB構造や負荷との兼ね合いでしょうが。

**Comment by fetus-hina** [comment]
- [ ] フィルタ
- [x] キルレシオ
- [x] 結果
- [ ] ブキ絞り込み

このリスト周りは他にもいろいろいじります
