### ISSUE TITLE
Hovering over Activity no longer displays number of battles

### ISSUE THREAD

**Issue by VGmaster670** [fetus-hina/stat.ink#1203]
exactly what it says on the tin

EDIT: Whoops just realized this is a duplicate

![image](https://user-images.githubusercontent.com/72361126/222304402-e800a1db-4ae7-451a-8fb4-4289b6f81edc.png)

**Comment by fetus-hina** [comment]
Not duplicated.
#1202 is an issue where the area is displayed blank.

I disabled it when I upgraded the library ([cal-heatmap](https://cal-heatmap.com/)), but I will do my best to re-enable it if that is what is needed.
https://github.com/fetus-hina/stat.ink/blob/59bdac652188a9332041507419c137807e6119b7/components/widgets/ActivityWidget.php#L90-L93
