### ISSUE TITLE
Add column containing submitter name to splatoon 3 csvs

### ISSUE THREAD

**Issue by cesaregarza** [fetus-hina/stat.ink#1207]
Hey,

I work in data science and have been playing around with the stat.ink csv outputs. One of the important pieces of data that's needed is the name (or unique ID works too) of the player or players who submitted the match.

This is because any statistical analysis would require to compensate for data imbalance. As an extreme example: if I was to submit 3,000,000,000 games, any analysis on this would be basically no different than analyzing just my data. Having a way to identify players who submitted the match would help a lot in compensating for this bias.

Thanks a lot!

**Comment by fetus-hina** [comment]
Currently, no player-identifying information is intentionally included.

When researching something, you should tally 7 people excluding "you (=`A1`)" or 3 of "your" teammates (= `A2`...`A4`) for each battle.
I think that is realistically sufficient, unless you have an impossible number of data, as in your example.

**Comment by cesaregarza** [comment]
Statistically that isn’t enough, the data imbalance is going to show up especially in any machine learning models.

But identifying information is not necessary, all that’s necessary is information to differentiate between players: hashing the player name + ID with SHA256 should be good enough to help compensate for data imbalance and sampling bias.
