### ISSUE TITLE
[Question] API to retrieve specific data from user

### ISSUE THREAD

**Issue by Leanny** [fetus-hina/stat.ink#1209]
Hello! I am looking for a way to get access to match stats for user X (I use `boolpotato` as example here because they appeared as most recent match.)

So far I found a way to get all match data of user X via the API with some filters, i.e. like [this](https://stat.ink/@boolpotato/spl3/index.json?f%5Blobby%5D=%21private&f%5Bresult%5D=win). Now I wonder if its possible to get all the results in a single json file, or how I am able to get the number of pages for the user.

Also I wonder if [this](https://stat.ink/@boolpotato/salmon3/stats/bosses?f%5Blobby%5D=%21private&f%5Bmap%5D=&f%5Bresult%5D=&f%5Bterm%5D=&f%5Bterm_from%5D=&f%5Bterm_to%5D=) can be accessed via API as well

Thank you

**Comment by fetus-hina** [comment]
- There is no way to obtain the numbers compiled as statistics.
- There is no way to retrieve the number of pages or battles/jobs number.
- Paging is enabled for the API.
  1. You can get the "page 2" data by adding a parameter `page=2` to the URL. (In practice, according to the Query String specification, the addition of `?` or `&` must also be added.)
  2. The retrieval phase ends when the data retrieved does not contain any data that you do not "know."
  3. After that, you can aggregate those data as you wish.

**Comment by Leanny** [comment]
Thank you
