### ISSUE TITLE
[Bug] Webhookの追加ができない

### ISSUE THREAD

**Issue by B4kedBr3ad** [fetus-hina/stat.ink#1212]
# 内容
- Discordの連携Webhookの追加ができない
- Discordのwebhookの末に/slackをつけたができず

# 再現手順
1. stat.inkのトップページからハンバーガーボタンをクリックする
2. プロフィールと設定をクリックする
3. Slack連携横の追加ボタンをクリックする
4. フィールドをすべて埋める（私はDiscordのwebhookのSlack互換を使用するため/slackをWebhookのURL末に追加 ）
5. 追加をクリックする
 
# 試したこと
- Cookie, Cacheの削除
- フィールドをすべて埋める
- ブラウザを変更する

# 問題が発生している環境
- Windows11 Chrome111
- Android10 Chrome110系
- Android10 Firefox110

**Comment by fetus-hina** [comment]
おそらく、チャンネルの指定が悪さをしていると思いますが、[Discord の Slack 互換エンドポイントは `channel` をサポートしていない](https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook) ので、Slack で動作するなら（あくまで互換機能なので）Discord 用の説明を追加するくらいかなと思います
