### ISSUE TITLE
Dictionaries Mapping Stages and Weapon Keys

### ISSUE THREAD

**Issue by TrevorBushnell** [fetus-hina/stat.ink#1217]
A long time ago I found dictionaries on the website that mapped the keys used in the csv files for weapons and game modes and stages to their English counterparts. I can no longer find those dictionaries on the website. Would someone be able to point me to where those dictionaries were as I would like to have an easy way to convert the keys used in the worldwide csv files to their English names for readability in my dashboard.

**Comment by fetus-hina** [comment]
Here's what you're looking for?

| Kind | URL |
|-|-|
| Stages | https://stat.ink/api-info/stage3 |
| Weapons | https://stat.ink/api-info/weapon3 |
| Lobbies (JSON) | https://stat.ink/api/v3/lobby |
| Modes (JSON) | https://stat.ink/api/v3/rule |

You can obtain those information by reviewing the specifications of the POST API.
- https://github.com/fetus-hina/stat.ink/wiki/Spl3-API:-Battle-%EF%BC%8D-Post
- https://github.com/fetus-hina/stat.ink/wiki/Spl3-API:-Salmon-%EF%BC%8D-Post
