### ISSUE TITLE
Mismatch in data between righthand info box and battle list summary

### ISSUE THREAD

**Issue by z2amiller** [fetus-hina/stat.ink#1218]
I noticed that the data in the right hand box in the battle log does not match with the summary in the battle log itself.
<img width="1126" alt="Screenshot 2023-05-03 at 8 30 26 AM" src="https://user-images.githubusercontent.com/155098/235979759-f0bcd27a-9d6e-4660-8d9c-90fb0d57e124.png">

For example, in my battle log focusing on Anarchy Open, it shows the same 1115 battles - in the summary it shows a 50% win percentage, but on the right hand box it shows a 47.5% win percentage.  The kill ratio is slightly different as well.   Maybe one of the two places is counting exempted battles differently?

**Comment by z2amiller** [comment]
I dug into this a little more, I think it's the way that the different boxes classify defeats.

Victory (507) / Victory (507) + Defeat (506) = 50.0% (observed in battle stat summary)
Victory (507) /  Victory (507) + Defeat (506) + Exempted (58) = 47.3%
Victory (507) / Victory (507) + Defeat (506) + Draw (44) = 47.9%
Victory (507) / Victory (507) + Defeat (506) + Draw (44) + Exempted (58) = 45.4%

The sidebar says 47.5% which actually isn't really a match for any of these outcomes, but I guess it's the closest (47.3%) to including exempted defeats as part of the total.

For what it's worth, I think the exempted defeats may also show up in the per mode/per weapon pie charts.

**Comment by fetus-hina** [comment]
The statistics used in the sidebar are based strictly on battles for which we have complete data.
For example, any kills or deaths not recorded are excluded, as are the battles has any disconnected players, either Good Guys or Bad Guys.
