### ISSUE TITLE
 統計（Xパワー）で計測中のバトル数が集計されていない

### ISSUE THREAD

**Issue by wkoichi** [fetus-hina/stat.ink#1221]
[統計（Xパワー）](https://stat.ink/@wkoichi/spl3/stats/season-x-power)を見たところ、#はその日のバトル数を表示していると思われますが、計測中でXパワーが決定していない場合に除外されているようです。3月9日に#は1となっていますが、実際には5で[リンク](https://stat.ink/@wkoichi/spl3?f%5Blobby%5D=xmatch&f%5Brule%5D=yagura&f%5Bterm%5D=term&f%5Bterm_from%5D=%401678320000&f%5Bterm_to%5D=%401678406400)を押すと、バトル数は5になっています。

<img width="671" alt="image" src="https://github.com/fetus-hina/stat.ink/assets/387175/d9c245af-6872-43d1-b869-d1ba0a9d7783">

**Comment by fetus-hina** [comment]
仕様です。
バトル数を表示しているのではなく、この件数のバトルの最大・最小がこれでした、と読んでください
