### ISSUE TITLE
Nintendo Network ID not displaying on profile

### ISSUE THREAD

**Issue by VGmaster670** [fetus-hina/stat.ink#1222]
Nintendo Network ID doesn't display on profile despite doing so previously
![image](https://github.com/fetus-hina/stat.ink/assets/72361126/c5fa6ff6-de3e-4e10-9243-e2e31a6eb4e9)
![image](https://github.com/fetus-hina/stat.ink/assets/72361126/26c9325c-e391-4fbe-aa8b-5729209fd096)
might be related to icons in dropdown menu not showing
![image](https://github.com/fetus-hina/stat.ink/assets/72361126/168a4d9d-2631-40e0-8868-cf9821bb46dc)

**Comment by fetus-hina** [comment]
They are removed.
The reason for this is indirectly mentioned in the blog, please see the latest news on the top page.
