### ISSUE TITLE
why the splatoon style icon has beed disappeared？

### ISSUE THREAD

**Issue by mjuijnm** [fetus-hina/stat.ink#1223]
Plaease recover this way to diskpaly，they are cute!!
I like the splatoon gold medal rather than the normal gold medal，
and battle ditail can diskplay everyone‘s equipment skill，they are effective ！

**Comment by fetus-hina** [comment]
Currently, there is serious risk in using images and other materials derived from Nintendo's assets.
The environment surrounding the tools around Splatoon has changed dramatically in the last few days.
It will never use icons derived from official assets again.
