### ISSUE TITLE
Twitch Extension

### ISSUE THREAD

**Issue by Scromx** [fetus-hina/stat.ink#1224]
Hello, 

would it be possible to have a Twitch extension of our stats?

**Comment by fetus-hina** [comment]
What do you actually need?

**Comment by Scromx** [comment]
I would like to be able to share information directly on twitch.

for example the Average Stats, 3/5 last match with a link to the match details, a link to the stat ink page.

**Comment by fetus-hina** [comment]
If there are people who want to do something similar, they will have different requirements, and there is also the issue of how it should look.
The easiest way is that you use stat.ink's API to get the data and process it as you wish.
