### ISSUE TITLE
Support Splatfest Player Crown, Player species and translate Challenges text

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#1227]
- [x] Splatfest Player Crown
- [x] Player species
- [x] Translations for event

**Comment by fetus-hina** [comment]
@frozenpandaman @spacemeowx2
Added species and crown type as attribute values for players structure.

| API | attr | values |
|-|-|-|
| battle | players.species | `"inkling"` or `"octoling"` |
| battle | players.crown_type | `"x"`, "`100x`" or "`333x`" |
| salmon | players.species | `"inkling"` or `"octoling"` |

The `crown_type` is as follows:

| key | meaning |
|-|-|
| `"x"` | Crowned Top 500 in X Battles |
| `"100x"` | Splatfest 100x battle winner |
| `"333x"` | Splatfest 333x battle winner |

The battle already has a `crown` attribute (boolean); `crown_type` is added as a complement to `crown`.

- If `crown_type` is set correctly, `crown` is automatically assumed to be truthy (="yes")
- If `crown` is truthy and `crown_type` is not specified, its type is assumed to be `"x"` (for compatibility with older clients)

API documents have been updated.
If you have any questions, please ask on this issue, on our discord server, or in a private channel.

Note that while those settings are reflected correctly on the API response, there is not yet a UI that can be properly displayed on a web page 😢

**Comment by frozenpandaman** [comment]
woohoo, yay, thanks! will get this supported sometime tonight or tomorrow before the fest...

**Comment by fetus-hina** [comment]
Close this issue as I can now remove it from my TODO list.
You guys may continue to write here if you have any questions.

**Comment by frozenpandaman** [comment]
@fetus-hina Just to clarify, unlike other attributes like `rank_in_team`, `kill`, etc. (which can be set both in the base payload _and_ in the players struct), have these keys have _only_ been added into the players struct? Or is it OK/expected to send it for both?

i.e. from the wiki API doc _"For the player themselves, the same data will be sent twice in the main structure and this player structure."_ – is this true for these new keys too?

(question applies to both regular battles and Salmon Run)

**Comment by fetus-hina** [comment]
They are added only to the player structure.
They are not particularly important information for the stat.ink user, so I have no plans to add them to the main structure.
However, stat.ink's system does not care about extraneous data, so there are no particular bad effects when you send them.
