### ISSUE TITLE
S-BLAST92 のブキグループは D+ のようです

### ISSUE THREAD

**Issue by splatoonstat** [fetus-hina/stat.ink#1231]
https://stat.ink/api-info/weapon3 によると S-BLAST92 のブキグループは D- に分類されていますが、ロングブラスターやオーバーフロッシャーなどの D+ ブキとマッチングすることが多く、おそらく D+ じゃないかと思います:pray:

**Comment by fetus-hina** [comment]
ありがとうございます。データを変更しました。
