### ISSUE TITLE
Ink Color statistics for Vs. Self Splatfest matches

### ISSUE THREAD

**Issue by Adrthegamedev** [fetus-hina/stat.ink#1233]
I've noticed that, due to excluding splatfest battles from [https://stat.ink/entire/ink-color3](https://stat.ink/entire/ink-color3) due to those being chosen by the user and not randomly chosen (i assume), Vs. Self battles (battles where the same splatfest team fights themself) are excluded from the ink color statistics, despite those being perfectly fine to add to the statistics due to the fact that the colors are chosen randomly again. The system could be changed to accomodate for this.

**Comment by fetus-hina** [comment]
The same teams' matchup does certainly use different ink colors than normal.
If the data is adopted, a **slight** increase in data volume would be expected.
The biggest problem is that I don't believe the results will be worth the complexity required to do it.
