### ISSUE TITLE
New Feature: Automatic Import

### ISSUE THREAD

**Issue by MichaelViveros** [fetus-hina/stat.ink#1236]
Hello!

I love stat.ink but forcing people to manually upload stats is a huge barrier to entry (especially since most Splatoon players aren't devs). Other video game stat sites like https://www.dotabuff.com/ support automatic import. And most players use that site as a result.

1. What are the "security reasons" for not supporting automatic import?
2. Would you be open to adding support for "automatic import"? I might be interested in helping.

**Comment by fetus-hina** [comment]
In short, you request the following.

  - Hina keep MY nso account information secure.
  - Hina should access SplatNet 3 on a routine schedule, using your own and your sponsor's resources, and not get in trouble with Nintendo.

I don't want to have as much control over other people's passwords and log-in tokens as possible, and I don't want to be sued by Nintendo.
Some of the third-party applications that manage them have already been warned by Nintendo and they have been removed from the store.

If you still think you need it, you can create a web service that does "SplatNet to stat.ink" periodic runs with your resources, after **you accept all the risks involved.**

**Comment by MichaelViveros** [comment]
Thanks for the reply. How could Nintendo sue someone for this? I’m just
surprised because that is not an issue for Dota/Valve.

And thanks for offering to potentially hook up stat.ink but I think if I do
try to build this then I won’t use stat.ink. I don’t want to make you do
something you’re not comfortable with.
