### ISSUE TITLE
`https://stat.ink/api/v3/salmon` が CORS を受け付けていない

### ISSUE THREAD

**Issue by murs313** [fetus-hina/stat.ink#1243]
こんにちは！
stats.inkの開発、そして長い間の保守ありがとうございます。

salmdroidのバックアップデータをstats.inkに送るwebアプリを作っていたのですが、`https://stat.ink/api/v3/salmon` が CORSを受け付けていないように見受けられました。
XMLHttpRequestを使って通信した際の、consoleに吐かれるエラー内容は下記です。
```
Access to XMLHttpRequest at 'https://stat.ink/api/v3/salmon' from origin 'https://127.0.0.1:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

他のエンドポイントは試していません。
過去に[こういったPR](https://github.com/fetus-hina/stat.ink/pull/770)があったので、エンドポイントごとに対応しているのかな？と思いましたが…🤔

とりあえずはcliツールにして回避しようと思っているので、急いだり優先したりしなくて良いのですが、ご報告まで。
また、昨今の規制の流れで改修するモチベがないとのことでしたらそれはそれで🙆🏻です。

**Comment by fetus-hina** [comment]
たぶんうごくようになったとおもいます

**Comment by murs313** [comment]
改修ありがとうございます！
preflightは通るようになったのですが、その先で問題があったので、 https://github.com/fetus-hina/stat.ink/issues/1244 を立てました。
