### ISSUE TITLE
Table salmon_boss3 should be in order of ID instead of name

### ISSUE THREAD

**Issue by howlagon** [fetus-hina/stat.ink#1245]
Currently, `salmon_boss3` is sorted alphabetically by name (Big Shot -> Stinger), which isn't the same as special weapons and bosses (ID 0 ascending). To match the style of the other tables, the ordering should be instead be ID_ASC. A table is listed below with the internal IDs and names

| ID | Name (EN) |
|--------|--------|
| 4 | Steelhead |
| 5 | Flyfish |
| 6 | Scrapper |
| 7 | Steel Eel |
| 8 | Stinger |
| 9 | Maws |
| 10 | Drizzler | 
| 11 | Fish Stick |
| 12 | Flipper Flopper |
| 13 | Big Shot |
| 14 | Slammin' Lid |

**Comment by fetus-hina** [comment]
It now has the data for such sorting.
However, the actual web page almost always prioritizes the number of appearances, etc., so it practically only works the way you want it to on the badge info page.
