### ISSUE TITLE
ギアパワーの合計が5.7を超えている例

### ISSUE THREAD

**Issue by StatsBeginner** [fetus-hina/stat.ink#1251]
ギアパワーの合計値が、フェスTを着ていなくても5.7を超える例があるのはなぜなのかって、おわかりになりますでしょうか？
たとえば、`2023-09-07.csv`の41行目（ヘッダ行を除くと40行目）の`A1-abilities`の内容は、

```
"{""swim_speed_up"":1.2,""run_speed_up"":1,""ink_saver_main"":0.6,""ink_recovery_up"":0.3,""ink_resistance_up"":0.3,""quick_respawn"":0.3,""quick_super_jump"":0.3,""special_saver"":0.3,""comeback"":true,""stealth_jump"":true}"
```

というものなのですが、カムバとステジャンを1としてカウントすると、合計が6.3になります。

5.7を超えるデータは全体で12〜13%程度あって、ほとんどはフェスT（`ability_doubler`）を着ているものなので、それは理解できます。フェスTのサブギアパワーが2倍になるので、6.6までは増えると思います。ただ上記は、フェスTを着ていない状態なのが謎です。

また、6.6より大きいものもあって、`ver5.0.0`以降で一番大きいのは7.8でした。
たとえば`2023-10-24.csv`の2行目の`A1-abilities`の内容は、

```
"{""quick_respawn"":2.4,""swim_speed_up"":1.6,""special_charge_up"":0.6,""ink_saver_main"":0.3,""ink_saver_sub"":0.3,""intensify_action"":0.3,""run_speed_up"":0.3,""ability_doubler"":true,""comeback"":true}"
```

となっています。
フェスT以外のサブギアパワーも2倍になるのかな？と思ったのですが、その場合は8.4が最大になると思うので、7.8最大というのもよくわからないですね。

全体的に、5.7を超えているのはフェス期間のデータなので、たぶんフェスの何らかの仕様なのかなとは思うのですが……。

とりあえず、
https://github.com/fetus-hina/stat.ink/wiki/Spl3-%EF%BC%8D-CSV-Schema-%EF%BC%8D-Battle
の一番下に

> The value indicates how many main-equivalent effects are achieved (a.k.a. "5.7 format"). The maximum is 5.7.
Such as Ninja Squid, set to true.

とあるのは、そうでもないような気がしました。

**Comment by fetus-hina** [comment]
原因はわからないのですが、追加ギアパワーが4つ以上ついているデータが存在するようです…

**Comment by fetus-hina** [comment]
おそらく、根本的には https://github.com/frozenpandaman/s3s/commit/c5aadb520795c7432d4f8cb475719d43b1d4c9bd に由来していると推定しています…

**Comment by fetus-hina** [comment]
とりあえず、最近のデータについては、[最初の3つの追加ギアパワーだけ見れば正しそう](https://github.com/fetus-hina/stat.ink/blob/77af18ee9fa138df90e9eee82084956dbfa2e5b6/components/helpers/GearConfiguration3Fingerprint.php#L42-L45)なことはわかったので、↑のコミットで最初の3つだけ見るように修正したつもりです。

現在、過去の全データを再出力中です。

**Comment by fetus-hina** [comment]
再生成が完了しました。
少なくとも改善はしていると思います。
（前のデータ作成時からサイト上で削除されたデータは今回の再生成で消えているので、少しだけデータは減っていると思いますが、そこは完全に仕様です）

**Comment by StatsBeginner** [comment]
なるほど、s3s側の過去のバージョンの細かいバグの影響がまだ残っていた的な感じですかね。
素早い対応いただきありがとうございます。
また、貴重なデータをご提供いただき感謝です。
