### ISSUE TITLE
バイト統計でクリア時の最大キケン度が実際の最大キケン度とは異なっている

### ISSUE THREAD

**Issue by wkoichi** [fetus-hina/stat.ink#1253]
https://stat.ink/@wkoichi/salmon3/stats/schedule?schedule=436

このスケジュールではクリア時の最大キケン度は285%でしたが、333%と表示されています。
いくつかのスケジュールを見てみましたが、すべて333%になっていました。

**Comment by fetus-hina** [comment]
すみません、なおしました…。

**Comment by wkoichi** [comment]
なおってました。ありがとうございます。
