### ISSUE TITLE
Error trying to upload Salmon Run jobs with new specials

### ISSUE THREAD

**Issue by Zekrom101** [fetus-hina/stat.ink#1258]
Error trying to upload Salmon Run jobs with new specials

Error uploading job. (ID: Q29vcEhpc3RvcnlEZXRhaWwtdS1hNWg2ZGltYW9wcnFjaWFuZ25tbToyMDIzMTEzMFQwNjIwMjVfNDVjMGNhYTMtODVjNS00Yzg5LTlmM2EtY2QyYWUyMmY4MTcx)
Message from server:
{
    "error": {
        "waves": "special_uses: Special Uses is invalid. unknown special unknown"
    }
}

**Comment by frozenpandaman** [comment]
I'll merge the PR into s3s tonight. Thanks!
