### ISSUE TITLE
Wrong period when match starts after period ended a few second

### ISSUE THREAD

**Issue by lin010151** [fetus-hina/stat.ink#1260]
The last match that started after period end won't show when I searched by selecting "Previous Period".
![Any Time](https://github.com/fetus-hina/stat.ink/assets/19383329/b9139fb3-7ba0-491d-bec1-c655412cacaf)
![Previous Period](https://github.com/fetus-hina/stat.ink/assets/19383329/5f58d140-3292-49fb-b2cc-4153a4d15260)

**Comment by fetus-hina** [comment]
Sorry for the inconvenience.
But, it is difficult to calculate correct periods by definition, so this is currently a "known-issue" and a fix is undecided.

**Comment by lin010151** [comment]
Maybe... 

Since there's only one match. If the match is the first match at the NEXT period, the LOBBY and the MODE are the same as "Previous Period", then put this match into "Previous Period". 

Would this work?

**Comment by fetus-hina** [comment]
I can implement it that way if we try hard, but it does not work as a whole.
First, that method does not work when searching. If we try to make it work that way, the query becomes too complex.

Another obvious edge case where the method does not work is when you start playing in a different mode at the last minute before the schedule switches.

**Comment by lin010151** [comment]
I see...
