### ISSUE TITLE
2023冬 Chill Season のノックアウト率が表示されない

### ISSUE THREAD

**Issue by splatoonstat** [fetus-hina/stat.ink#1261]
[ノックアウト率](https://stat.ink/entire/knockout3?season=6) で "2023冬 Chill Season" を選択するとグラフが表示されなくなっているようです。

![stat ink_entire_knockout3_season=6](https://github.com/fetus-hina/stat.ink/assets/126483629/f11257a9-c167-4620-b1ca-143295cac5db)

**Comment by fetus-hina** [comment]
あら…。
手動で実行したらとりあえず集計はできるみたいなので、たまたま秘孔をついたのかなんなのか…。

数時間ごとに再実行がスケジュールされているので、とりあえず様子を見ます

**Comment by fetus-hina** [comment]
どうやら11月末あたりからバッチ処理の一部がまともに動いていなかったようです
サーバーの設定を変更したので動作するようになったはずです
