### ISSUE TITLE
Small composer suggestion

### ISSUE THREAD

**Issue by arokettu** [fetus-hina/stat.ink#1263]
https://github.com/fetus-hina/stat.ink/blob/2f1010596691bfbc1c16410f6a47e17a4d70646a/composer.json#L75

^ no real need to do that, it already installs [an empty metapackage](https://packagist.org/packages/arokettu/random-polyfill#1.99.0) (v1.99) on PHP 8.2+

**Comment by fetus-hina** [comment]
Yes, you are completely correct and thanks for your useful project.

I have decided to clearly exclude 100%-unnecessary-polyfill-packages in the maintenance of this project and one of them is your package.
The meta-package you created certainly does nothing, but I chose to do nothing more than that, to "not install" it. That's all.
