### ISSUE TITLE
ジムワイパー・ヒューの英名は Splatana Stamper Nouveau に変更されました

### ISSUE THREAD

**Issue by splatoonstat** [fetus-hina/stat.ink#1264]
v7.0.0 でジムワイパー・ヒューの英名が Neo Splatana Stamper から Splatana Stamper Nouveau に変更されたようです。

> ![image](https://github.com/fetus-hina/stat.ink/assets/126483629/95789520-5e93-456c-8f7b-51014466d2cb)
> [Nintendo Support: How to Update Splatoon 3](https://en-americas-support.nintendo.com/app/answers/detail/a_id/59461/~/how-to-update-splatoon-3#v700)

[Splatana Stamper Nouveau - Inkipedia, the Splatoon wiki](https://splatoonwiki.org/wiki/Splatana_Stamper_Nouveau#Etymology) によると他の言語も変更されていそうです。

**Comment by fetus-hina** [comment]
@hacceuee
This guy reported Neo Splatana Stamper has been renamed Splatana Stamper Nouveau.
Does your project plan to follow this renaming?

**Comment by hacceuee** [comment]
I'm glad they changed that! It was bothering me that it was a Nouveau brand weapon with a Neo brand name. s3-pixel-icons has been updated to 2.3.10 with it renamed to Splatana Stamper Nouveau (6d41c236f2a2f78bb5d7b0d5b9a1e2651a7a7c7d)
