### ISSUE TITLE
Export times out after ~8mb.

### ISSUE THREAD

**Issue by z2amiller** [fetus-hina/stat.ink#1265]
I have 10,000 games logged in stat.ink.  (Username: Squidaddle  https://stat.ink/@Squidaddle/spl3)

I recently discovered the 'export' functionality, and I've tried to use it a few times.

Whenever I use the 'export' function, it downloads about 8mb very fast, then it will download maybe ~1mb more, up to about 9mb, then stops and the network times out.

I've tried in both Chrome and Safari.  (Safari seems to take longer before it times out)
I poked around in the code and didn't see anything obvious that would be limiting it.  Maybe the PHP implementation has a resource cap per request that is being exceeded.
Maybe it's settable in the php.ini, but I haven't used php in quite a few years so don't know if this is modern.

https://www.php.net/manual/en/ini.core.php#ini.memory-limit

I imagine the total size will be somewhere around 32 megs of compressed json, because the current download fails after about 3,000 out of my 10,000 battles, and contains:

```
$ ls -l statink-Squidaddle.json.gz
-rw-r--r--@ 1 xxxxxxxx  primarygroup  9788241 Mar 25 14:51 statink-Squidaddle.json.gz
$ gzcat statink-Squidaddle.json.gz |wc
gzcat: statink-Squidaddle.json.gz: unexpected end of file
gzcat: statink-Squidaddle.json.gz: uncompress failed
    2889  614177 59401108
```

(2889 lines, 614k tokens, 59mb)

I guess I'm probably a power-user and you can't help, but it would be awesome to be able to get at my stats.  Maybe it would help to apply some filters by time/weapon type/etc to break it into smaller chunks. (e.g. month/day at a time)

**Comment by fetus-hina** [comment]
I have seen such problems before and I think it is probably a problem in the h2o web server, not in PHP.
I think your suggestion is worthwhile and I will see what I can do to help.

**Comment by z2amiller** [comment]
Thanks so much for checking!

If you think it's the h2o server itself, it looks like it's supposed to spool into [/tmp](https://h2o.examp1e.net/configure/base_directives.html#temp-buffer-path) after 32 megs of data.
Maybe the /tmp directory on your host is almost full or slow somehow?

You can increase the amount of memory it'll use before sending to disk with [temp-buffer-threshold](https://h2o.examp1e.net/configure/base_directives.html#temp-buffer-threshold).

**Comment by z2amiller** [comment]
I saw your message that you'd migrated the server and tried another export.  It worked!  It exported > 13,500 games, and the download was ~46MB.  Thank you!
