### ISSUE TITLE
[Salmon Run] Triumvirate option not implemented, resulting in upload errors

### ISSUE THREAD

**Issue by TheGreatAndPowerfulWeegee** [fetus-hina/stat.ink#1297]
I apologize if this is redundant considering it is already planned to be added, but salmon run matches featuring triumvirate do not upload, likely due to the site not supporting it at this time.

`Error uploading job. (ID: Q29vcEhpc3RvcnlEZXRhaWwtdS1hbnlqcHlyNzNrajNic2ltZHJtbToyMDI0MDYwOFQwMzI5NTJfYTFhMDA0NDctMmIyMi00ODhlLWI1ZWMtMTJiNDBiMzI2MjNk)
Message from server:
{
    "error": {
        "king_salmonid": "King Salmonid is invalid."
    }
}`

**Comment by fetus-hina** [comment]
Thank you for letting me know.
I have fixed this issue.
I believe you should now be able to upload data.
