### ISSUE TITLE
個人の統計ページの改善希望点

### ISSUE THREAD

**Issue by hasegaw** [fetus-hina/stat.ink#13]
１）
各グラフには勝数・負数、合計数を整数値で記述する。

２）期間による絞り込み

チェックボックスで下記からの選択で期間絞り込み。

・最新ニュース以降※
・ひとつ前のニュース以降※
・３時間以内
・６時間以内
・今日 (yyyy/mm/dd)
・昨日 (yyyy/mm/dd)
・yyyy/mm/dd
・....

※ガチマッチだと、このタイミングでゲームルールが変わるので、このタイプの期間選択が
　あるととてもうれしい

**Comment by fetus-hina** [comment]
- [x] グラフ表示改善
- [ ] 期間による絞り込み

統計は「絞り込みフィルタを通して」、「任意の1-2項目で集計して」、「任意の項目を表示」が出来るといいなあ、と。
例： ガチマッチでフィルタして（ガチマッチのみを対象に）、「マップ」と「ルール」で集計して、勝率を表示（二次元）

**Comment by fetus-hina** [comment]
2a8b43a97e64a64da6e463090b3fb496b67f4771 でとりあえずいろいろ絞り込めるようになったので、将来構想はともかくとしてこのissueは閉じます
