### ISSUE TITLE
リールガン系統のブキカテゴリーはシューターのようです

### ISSUE THREAD

**Issue by splatoonstat** [fetus-hina/stat.ink#1306]
https://stat.ink/api-info/weapon3 ではリールガン系統のブキカテゴリーはリールガンとなっていますが、ゲーム内およびイカリング3ではリールガンというカテゴリはなく、シューターカテゴリーに分類されるようです。

![IMG_1977](https://github.com/fetus-hina/stat.ink/assets/126483629/0fe6e661-8b4b-45b9-9517-b5afba4f235f)

**Comment by fetus-hina** [comment]
この設定は意図的です。
