### ISSUE TITLE
Support Conch Clash in Splat Fest

### ISSUE THREAD

**Issue by mad-p** [fetus-hina/stat.ink#1324]
From Summer Fest 2024, a new fest mode Conch Clash is introduced.
There expected at least three modes
- `ホラガイ争奪戦` 1x
- 10x
- 33x

Should introduce new values in `fest_dragon` or a new field?

**Comment by fetus-hina** [comment]
Support for Conch Clash has been implemented.
If the clients' implementation is completed by the next fest, it should work for Food Fest and Grand Fest.

The API now includes `conch_clash`, and its value will be either `1x`, `10x`, or `33x`.
If it is not a Conch Clash, it expects either a `null` setting or the absence of the `conch_clash` key in the JSON/MsgPack object.
