### ISSUE TITLE
Add Brazilian Portuguese translation (volunteer)

### ISSUE THREAD

**Issue by Ant-Spl** [fetus-hina/stat.ink#1340]
I'd like to volunteer to translate stat.ink to Brazilian Portuguese pt-BR. The translation would be done following the current state of the English version of the website with corrections if needed. I've already translated Splatoon 3 Gear Seed Checker and Sendou.ink to my language as well.

Thank you very much.

**Comment by fetus-hina** [comment]
Thank you.

You can pick one of the messages directories and copy it to the pt-BR directory to work on, or you can use the contents of [the branch I have created as a base](https://github.com/fetus-hina/stat.ink/tree/lang-pt-br/messages/pt-BR).
(You do not necessarily need to use this branch.)

No need to finish all translations at once.

**Comment by Ant-Spl** [comment]
No worries! I'll take my time to make sure everything is okay.
Thank you very much for providing the base. Here I go!

**Comment by fetus-hina** [comment]
#1346

**Comment by fetus-hina** [comment]
@Ant-Spl
Thank you again,

PR #1346 has been merged and deployed.
If you have additional translations, please create another PR.

Also, I'm reflecting translations from you guys and from the Spanish catalog to create and reflect translations for a private project that creates thumbnail images, etc. for the top page and details page.
If you have any suggestions, please let me know.

<details><summary>for battle results</summary>

```php
<?php

declare(strict_types=1);

return [
    'DEFEAT' => 'Derrota',
    'DRAW' => 'Empate',
    'KNOCKOUT!' => 'Knockout!',
    'Score: {count}' => 'Pontuação: {count}',
    'VICTORY' => 'Vitória',
    '{percent}%' => '{percent} %',
    '{point}p' => '{point} p',
];
```
</details>
<details><summary>for salmon run results</summary>

```php
<?php

declare(strict_types=1);

return [
    'Clear!' => 'Victoria!',
    'Defeat' => 'Derrota...',
    'Hazard Level' => 'Nível de Hazard',
    'Hazard Level MAX!' => 'Nível de Hazard MÁX!',
    'High Tide' => 'Maré alta',
    'Low Tide' => 'Maré baixa',
    'Normal' => 'Maré média',
    'Private Job' => 'Partida Privada',
    'Wave {waveNumber}' => '',
    'XTRAWAVE' => '',
];
```
</details>
