### ISSUE TITLE
0k/0dのときキルレシオが1.00になっている

### ISSUE THREAD

**Issue by wkoichi** [fetus-hina/stat.ink#172]
￼￼￼https://stat.ink/u/wkoichi/1784544

チーム成績の方は、0k/0dだとキルレシオが空白になっていますが、個人成績の方はキルレシオが1.00になっています。

![image](https://cloud.githubusercontent.com/assets/387175/17649645/2879f738-6275-11e6-8aa7-098d9bf085ab.png)

![image](https://cloud.githubusercontent.com/assets/387175/17649648/38252248-6275-11e6-9fc6-db996958bb25.png)

**Comment by wkoichi** [comment]
一覧にキルレシオを出したときに、空白だと変なので意図的にこうしているような気がしてきました。そうでしたら、お手数ですがクローズしてください。

**Comment by fetus-hina** [comment]
はい、意図的なものです。0/0 の時、表示に適するものはありません。
（厳密には、0 death の時点で妥当なものはありません）
むしろ1.0表示の方がおかしいのですが、そっちはバトル一覧表示のキルレ表示が微妙なことになるのを避けるため便宜的に1.0にしているものにひっぱられています。

なお、0デスの時の扱いとしてよく行われるのは次の計算のようです。

- 諦める(空白、N/A)
- キル数+1 (3k 0d の時 4.0)
- 無限
