### ISSUE TITLE
ステージごとのブキ使用率表

### ISSUE THREAD

**Issue by sennuma** [fetus-hina/stat.ink#175]
ブキ統計から各ステージにおいてのブキ使用率が見られるが、ステージの統計からは見られない。
例えば、シオノメ油田ではどのブキがx%使われている、どのブキがx%使われている… といった表ないしはグラフがあると良いと思う。

**Comment by fetus-hina** [comment]
現在/次のステージに関してトップページで表示を開始しました。(v1.99.0)
統計ページはv1.100で変更する予定です。

**Comment by sennuma** [comment]
返信ありがとうございます。いつも貴サービスを利用させて頂いております。

統計画面の事項、了解致しました。私の愚見を採用して頂きありがとうございます。

**Comment by fetus-hina** [comment]
ブキ使用率は v1.100.0 で実装され、2017-01-01 リリースで反映されます。
勝率等の統合は以後実装します。
この issue はしばらく open のままにしておきます。
