### ISSUE TITLE
スペシャル使用回数のパラメーターがドキュメントと異なっています

### ISSUE THREAD

**Issue by kakunpc** [fetus-hina/stat.ink#215]
https://github.com/fetus-hina/stat.ink/blob/master/doc/api-2/post-battle.md#post-apiv2battle

specials | 整数(0～) | プレーヤーのスペシャル使用数を指定します。(Splatoon 2仕様のスコアボード用)
-- | -- | --

とのことですが、'specials' ではなく 'special' が正しい？

**Comment by fetus-hina** [comment]
`special` が正しいです。すみません。

**Comment by kakunpc** [comment]
ありがとございます。
ツール側の方直しときます
