### ISSUE TITLE
[2] User stats data do not update automatically when post a battle

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#255]
New users only? example: https://stat.ink/@PKfuzzy/spl2

**Comment by fetus-hina** [comment]
- [x] Fix code
- [ ] Fix stats for users

**Comment by dofine** [comment]
Yes, same problem here. Newly registered account a few days ago.

**Comment by fetus-hina** [comment]
Your stats data looks updated. (This issue's "stats" meaning sidebar's battles, win %, ...)
If you meaning (when commented):
- "Sidebar displays nothing": Your stats have been updated when post a battle (after commit f7d1ae1a5dddd65e80df6ccf8ff3ed549dcb5bf5).
- "Sidebar displays mismatch 1 battle": Please see #263 
- others: Could you comment below about what meaning?

**Comment by dofine** [comment]
Sorry, I mean #263. Sidebar match count is 1 less than the main frame.
