### ISSUE TITLE
[2] Import SplatNet's JSON format and related data

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#256]
- [ ] Create a column for ID-number on `battle2` table like `"battle2"."splatnet"` to reduce duplicate
  - [x] Add
  - [ ] Reduce
- [x] Add fields on the API
  - [x] SplatNet's Battle ID-number (unique on user and number)
  - [x] SplatNet's JSON
  - [x] SplatNet users' ID each `battle_player2`
  - [x] SplatNet team ID
- [ ] JSON parser

**Comment by dofine** [comment]
Hi I've been playing with the two tools you provided on the homepage. So the result is that I got double * 50 battles. 😭 Will the battle `start_time` or `battle_number` be used as something like primary key to reduce duplicate?

**Comment by fetus-hina** [comment]
Please wait until implementing the `"battle2"."splatnet"`...

**Comment by fetus-hina** [comment]
Note: sort order https://github.com/frozenpandaman/splatnet2statink/issues/6
