### ISSUE TITLE
Private Battles on listing don't show KO status

### ISSUE THREAD

**Issue by hymm** [fetus-hina/stat.ink#266]
For ranked battles and league there is usually a `KO` or `Time` beside `Win/Loss` status in the list view.  For private battles this status is not shown.  See:

https://stat.ink/@Locke/spl2?filter%5Brule%5D=private-private-any&filter%5Bmap%5D=&filter%5Bweapon%5D=&filter%5Brank%5D=&filter%5Bresult%5D=&filter%5Bterm%5D=&filter%5Bterm_from%5D=&filter%5Bterm_to%5D=&filter%5Btimezone%5D=Europe%2FLondon

**Comment by fetus-hina** [comment]
Bug note:

It checks `Battle2::$isGachi` https://github.com/fetus-hina/stat.ink/blob/196623fefa905ce72773249664753aa51e6c2b4f/views/show-v2/battle.tablerow.tpl#L93

The code of `isGachi` https://github.com/fetus-hina/stat.ink/blob/196623fefa905ce72773249664753aa51e6c2b4f/models/Battle2.php#L929

It checks `Battle2::$mode->key` and it is `private` when Private Battle.
It should check `Battle2::$rule->key`.

**Comment by fetus-hina** [comment]
This issue has been fixed. Thank you for the report.
