### ISSUE TITLE
Don't subtract bonus 1000p from points on the inked column of the battles list and battle details

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#271]
- [ ] Battle list
- [ ] Battle details

Now, the `my_point` field is also used for Turf Inked on Ranked Battle.
Squid Tracks sends the point data that including bonus 1000p, but it's a bug and stat.ink should display as is.

Battle list:
https://github.com/fetus-hina/stat.ink/blob/55fb332cd602e03b1d0a45faf8a0e3a0fcce21d8/views/show-v2/battle.tablerow.tpl#L155-L159
https://github.com/fetus-hina/stat.ink/blob/55fb332cd602e03b1d0a45faf8a0e3a0fcce21d8/models/Battle2.php#L903-L917

Battle details:
https://github.com/fetus-hina/stat.ink/blob/55fb332cd602e03b1d0a45faf8a0e3a0fcce21d8/views/show-v2/_battle_details.php#L361-L383

**Comment by hymm** [comment]
not sure if this is a different issue, but when p inked is below a thousand it doesn't display on the battles list.

![image](https://user-images.githubusercontent.com/2180432/29993574-bd163000-8f6f-11e7-90f7-32005f0ca5a4.png)

**Comment by fetus-hina** [comment]
It's an expected behavior related to this issue.

1. As of now, stat.ink doesn't strictly supported Turf Inked data for Ranked battles. It assumes work in the Turf War mode.
2. The website subtracts 1000 from points if the battle is won.
3. If the (subtracted) points to be a negative value, it's an error and displays nothing.

The code in which this behavior is written is in `stat.ink/models/Battle2.php`:908-914 above.

After support Ranked Battles (= resolved this issue), it will display as-is. So it will be resolved.
