### ISSUE TITLE
Error deleting duplicate records

### ISSUE THREAD

**Issue by Tiryoh** [fetus-hina/stat.ink#278]
I got an error shown below when I was going to remove duplicate records.

```
An internal server error occurred.
```

These are the target records.
https://stat.ink/@tiryoh/spl2/104459
https://stat.ink/@tiryoh/spl2/104458

I suppose this error could be same as these issues.
https://github.com/fetus-hina/stat.ink/issues/245
https://github.com/fetus-hina/stat.ink/issues/262

**Comment by fetus-hina** [comment]
This issue was fixed with the commit above.
Please try it again.

If fixed, please close this issue.
If not, please post a comment.

**Comment by Tiryoh** [comment]
Thank you for your quick response!
It became available to remove duplicate records.
