### ISSUE TITLE
APIキーの再生成ができない

### ISSUE THREAD

**Issue by blueberrystream** [fetus-hina/stat.ink#309]
## 🔍 現象
- ログイン済みの状態で https://stat.ink/profile の「APIキーの再生成」ボタンを押すと `Method Not Allowed. This URL can only handle the following request methods: POST.` とエラーメッセージが表示されるページに遷移する

![2017-12-20_19-31-55](https://user-images.githubusercontent.com/1652533/34202927-a08f4068-e5bc-11e7-936c-6a69c7549bc4.png)

## 🏃 試したこと
- ブラウザーのExtensionの影響かと思い、iPhoneのChromeで試すも同様でした

**Comment by fetus-hina** [comment]
修正できているとおもいます。ご確認ください。
ご迷惑をおかけしました。

**Comment by blueberrystream** [comment]
ご修正ありがとうございます！確認いたしました！
迅速なご対応ありがとうございました！
