### ISSUE TITLE
filterの期間指定の仕様

### ISSUE THREAD

**Issue by roto5296** [fetus-hina/stat.ink#314]
いつもありがたく使わせて頂いております

1つ質問&要望なのですが、
battleの期間指定によるfilter (https://github.com/fetus-hina/stat.ink/blob/master/models/Battle2.php#L277-L319 )で`battle2.created_at`を用いているのはなぜでしょうか

できれば
https://github.com/fetus-hina/stat.ink/blob/master/actions/show/v2/UserStatReportAction.php#L126-L131
のような日時をもとにfilterしていただきたいです

というのもバトルレポート画面からイカログ画面に遷移した時、バトルが見つからないことが多々あるためです。

よろしくお願いします

**Comment by fetus-hina** [comment]
理由としては、「(元のコードであるSplatoon 1 用を) 作った時期によるもの」（≒具体的な理由はない）というのがほぼすべてです。

基本的には対応する方向でいきたいのですが、いろいろと考える必要があるところでもあるので、少々お待ちいただければと思います。
