### ISSUE TITLE
Lower case username

### ISSUE THREAD

**Issue by martinemde** [fetus-hina/stat.ink#315]
My wife accidentally set her @username to a capital, and now we have to be careful to type it with a capital letter every time.

Is it possible to set all usernames to lowercase? The display name would still retain case but the username could be case insensitive.

**Comment by fetus-hina** [comment]
Generally:
No. I can't update `@screen_name`s to lower case (or case independent).
Stat.ink has a lot of users and there are several users use same `@screen_name` with different case only.
For example, it has `@taka`, `@Taka` and `@TAKA`. There are about 30 other `@screen_name`s like this at this time.


To your wife:
I can update her `@screen_name` to lower case (if no one use it).
If you and she wish so, please contact me **by email** (for security reasons).
Please include the following information to the email:
  - Her current `@screen_name` (Of course needed)
  - First few (about 10) letters of API token (I'll use this to identify her)

**Comment by martinemde** [comment]
Thank you! 🦑🔫🦑
