### ISSUE TITLE
Internal Server error on /@Kewe/spl2

### ISSUE THREAD

**Issue by martinemde** [fetus-hina/stat.ink#320]
Happy Splatfest!

This happened at about the same time as Shellendorf. Maybe bad data?

Mine is also an internal server error for the same page: https://stat.ink/@martinemde/spl2

Also, is it possible to fix records that went in as `?` for the map because I was using an old splatnet2statink? I'm guessing it's related.

**Comment by fetus-hina** [comment]
Sorry for inconvenience.
It's been fixed in https://github.com/fetus-hina/stat.ink/commit/5836f53d2c86a655a1bdabbc467d93568d7529fc
Thank you for reporting the issue.

**Comment by martinemde** [comment]
@fetus-hina Thank you!
