### ISSUE TITLE
Add to cause of death list: Cannon

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#324]
![](https://user-images.githubusercontent.com/848666/35766642-36fe28a4-091f-11e8-8543-3476f3f3af37.jpg)
キャノン で
やられた！
https://twitter.com/SplatoonJP/status/959351852616769536

**Comment by frozenpandaman** [comment]
Called "Cannon" in English too
![image](https://user-images.githubusercontent.com/7245874/37554029-ed5229bc-298f-11e8-9bfa-6e336641bc10.png)

**Comment by fetus-hina** [comment]
Thank you for the information :+1:. I've updated translation files (for non-English/Japanese locales).
