### ISSUE TITLE
add ink turfed, specials, assists to summary on splat log

### ISSUE THREAD

**Issue by hymm** [fetus-hina/stat.ink#330]
Is it possible to add turf inked, specials, and assists on the user splat log summary?

![image](https://user-images.githubusercontent.com/2180432/37360027-5654ea9e-26ac-11e8-8cb4-5ab06050d322.png)

**Comment by fetus-hina** [comment]
I would like to add them.

**Comment by fetus-hina** [comment]
Added them in faf9f05b59e37804da7d47db416f68bc6e3ecef9
But it looks something wrong on "Turf Inked" part.
I'll check data & logic later.

**Comment by hymm** [comment]
I checked with google sheets and most of the statistics match.  However the standard deviations for all the numbers seem to be a bit off.

![image](https://user-images.githubusercontent.com/2180432/37540146-34077fce-2913-11e8-9af8-ec2f30a6cb98.png)

https://stat.ink/@hymm/spl2?filter%5Brule%5D=&filter%5Bmap%5D=&filter%5Bweapon%5D=&filter%5Brank%5D=&filter%5Bresult%5D=&filter%5Bterm%5D=24h&filter%5Bterm_from%5D=&filter%5Bterm_to%5D=&filter%5Btimezone%5D=America%2FLos_Angeles

**Comment by fetus-hina** [comment]
Stat.ink calculates a "population standard deviation" and it looks Google Spreadsheet calculates a "sample standard deviation."
Google Spreadsheet may returns same value if you use `STDEVP` instead of `STDEV`. (Not tested)
