### ISSUE TITLE
add support for new x rank splatnet parameters

### ISSUE THREAD

**Issue by hymm** [fetus-hina/stat.ink#339]
https://gist.github.com/hymm/5d4b8b9610da864de4f8c4663f7602e4

There are some new parameters for x rank.

* rank: worldwide rank of player (1 would be #1 top player)
* crown_players: players in room that are top 500 (unconfirmed)

**Comment by hymm** [comment]
1. should I use `estimate_gachi_power` for `estimate_x_power`?
2. should I use `x_power_after` for `splatnet x_power`?

**Comment by fetus-hina** [comment]
I talked with @frozenpandaman about that.

- `x_power` or `x_power_after`: Maybe `after`, but I'm not confirmed that. (I'm standing B zone 😀 )
- I'll add `estimate_x_power` parameter. You can send this now. (It'll simply ignore until implement it)
- "crown_players": I'll add `top_500` parameter (tri-bool value, `"yes"`, `"no"` and `null`/empty) for each player ("players" structure). You can send this now.
- "rank": Nothing decided at this time.
