### ISSUE TITLE
Line Graphs for Ranked Modes

### ISSUE THREAD

**Issue by matthewwithanm** [fetus-hina/stat.ink#347]
I really like [the line graphs for turf war][1]; they help me see how I'm improving over time. In contrast, the ranked mode graphs just show win/loss. Can we get line graphs that show our performance over time for the ranked modes?

Thanks!

[1]: https://stat.ink/@matthewwithanm/spl2/stat/nawabari

**Comment by fetus-hina** [comment]
Sorry I made you wait... I've implemented this feature. :tada:

**Comment by matthewwithanm** [comment]
awesome! thanks!!
