### ISSUE TITLE
Slack連携のWebhook URLにDiscordのものも指定できるようにする

### ISSUE THREAD

**Issue by YDKK** [fetus-hina/stat.ink#349]
いつも便利に使わせていただいております．

Slack連携についてなのですが，Discordに対しても連携できるようになると便利だと思います．  
こちらにあるように，DiscordではSlack互換のWebhookを提供しています．  
https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook

そのため，ここで行っているURLチェックに対して， `https://discordapp.com/api/webhooks/` から始まるものも許可するようにすることで対応できると思われます．  
https://github.com/fetus-hina/stat.ink/blob/23a167a8a4d559adb05f0d179c1a207924f4c72b/models/SlackAddForm.php#L81-L86

是非ご検討のほどよろしくお願いします．

**Comment by fetus-hina** [comment]
Webhook URL として、Discord のものが指定できるようになりました

**Comment by frozenpandaman** [comment]
Cool!
