### ISSUE TITLE
スペシャル使用回数について

### ISSUE THREAD

**Issue by tkgstrator** [fetus-hina/stat.ink#356]
https://stat.ink/@me/spl2/986534

https://stat.ink/api/v2/battle?older_than=986535&count=1

リザルトページでみると正しく自分を含めた8人のプレイヤーのスペシャル使用回数が表示されているのですが、JSON側ではスペシャル使用回数がアシスト込みのキル数と一致してしまっていて、正しいスペシャル使用回数が取得できません。

**Comment by fetus-hina** [comment]
ご指摘ありがとうございます。修正しました。
