### ISSUE TITLE
Chinese version?

### ISSUE THREAD

**Issue by sunoru** [fetus-hina/stat.ink#357]
Hello,
I'm a Splatoon player and a coder from China. stat.ink is a great work and I'd love to help add a Chinese version for it. Can I just fork your code and add the language? Do you have any suggestions?

**Comment by sunoru** [comment]
By the way, I have read the wiki page. In most cases Chinese is also kind of special that no one use `zh` and `zh-TW` instead of `zh-CN` and `zh-TW`. Can I keep this convention?

**Comment by fetus-hina** [comment]
Hello!
I've created Chinese languages (both simplified and traditional) files to my repo's "chinese" branch.
https://github.com/fetus-hina/stat.ink/tree/chinese/messages /zh-CN and /zh-TW

Please **do not** translate proper nouns (e.g. weapons, gears, stages, ...) until Splatoon 2 released in China or Taiwan.
Probably, I think you will translate mainly on `app.php`.

**Comment by sunoru** [comment]
Yeah, I see. Thanks!

**Comment by sunoru** [comment]
I found that actually there are also some words in the UI officially defined in SplatNet, such as "Good guys" and "Bad guys". I wonder if these terms should be treated as proper nouns.
