### ISSUE TITLE
X Power Not In Graphs

### ISSUE THREAD

**Issue by matthewwithanm** [fetus-hina/stat.ink#364]
Am I crazy or is X-Power not actually being rendered in the graphs?

<img width="886" alt="screen shot 2018-10-03 at 10 51 48 pm" src="https://user-images.githubusercontent.com/126263/46455260-0c7ae000-c75f-11e8-991a-17c9d05ffcaa.png">

**Comment by fetus-hina** [comment]
It needs 2 or more X-power data (for each mode).  
In your TC achievements, X power is registered only for [this battle](https://stat.ink/@matthewwithanm/spl2/1412521).

[This](https://stat.ink/@matthewwithanm/spl2?filter%5Brule%5D=standard-gachi-yagura&filter%5Brank%5D=x) is your TC history in rank X.
And this is why your x-power doesn't render:
![](https://user-images.githubusercontent.com/848666/46459551-33cfbc80-c7f4-11e8-8271-8de8134fa90b.png)

**Comment by matthewwithanm** [comment]
Ah, thanks! I figured it needed two or more but didn't realize 1.2 didn't support it. Thank you!
