### ISSUE TITLE
Require of filter function in get-battle API

### ISSUE THREAD

**Issue by yunyang088** [fetus-hina/stat.ink#366]
https://github.com/fetus-hina/stat.ink/blob/master/doc/api-2/get-battle.md

I'm an iOS developer and prepare to build an iOS app for stat.ink.

I read the public API and It seems that the get-battle API doesn't accept any filter options. Are there any more functional APIs for me to build an app?

**Comment by fetus-hina** [comment]
Unfortunately "no", as of now.
I am busy with work now and current top priority task is Salmon Run.
But filters are necessary, so we will create them later.
