### ISSUE TITLE
GET api/v2/battle で splatnet_json = null になる

### ISSUE THREAD

**Issue by mak4026** [fetus-hina/stat.ink#369]
いつもありがたく利用させていただいております。

`GET api/v2/battle` について
https://stat.ink/api/v2/battle/1492885
のようにbattleを単体で取得すると `splatnet_json`の中身がある場合にも、
https://stat.ink/api/v2/battle?older_than=1492886&newer_than=1492284
などのように範囲で取得すると `splatnet_json`が必ず`null`になることを確認しております。
これは仕様でしょうか？

**Comment by fetus-hina** [comment]
レスポンスのサイズがあまりにも巨大になるのを防ぐため、一覧取得時には意図的に null を設定しています。

**Comment by mak4026** [comment]
ご返信ありがとうございます。失礼いたしました。
