### ISSUE TITLE
`POST /api/v2/salmon`の重複処理について

### ISSUE THREAD

**Issue by kamiyaowl** [fetus-hina/stat.ink#374]
素晴らしいシステムをありがとうございます。

ベータ版ということで恐縮なのですが[POST /api/v2/salmon](https://github.com/fetus-hina/stat.ink/blob/master/doc/api-2/post-salmon.md)にすでに追加済のデータを投げても`201 Created`が返却され、登録されてしまう現象が発生しています。これは仕様でしょうか。

https://stat.ink/@kamiya_owl/salmon/501
https://stat.ink/@kamiya_owl/salmon/500
https://stat.ink/@kamiya_owl/salmon/493
https://stat.ink/@kamiya_owl/salmon/444

※`splatnet2statink / 1.3.0`を使用

**Comment by fetus-hina** [comment]
現時点で、同一の登録をはじくような処理は未実装です。
（`302 Found` を返す仕様は定義はしていますが決して返されることはありません）

ただし（splatnet2statink のソースを見る限りまだ利用されていないようですが）、
登録済みのバトル番号（上記リンクでは 1186）を取得するAPI
（`GET /api/v2/user-salmon?only=splatnet_number`）は動作していますから、
クライアントで「すでに登録している番号を再送信しない」実装は可能です。

この実装要求は @frozenpandaman に feature request してみてください。

**Comment by kamiyaowl** [comment]
ありがとうございます。早速実装してリクエストしてみることにしました。
[Support Salmon Run -r flag #70](https://github.com/frozenpandaman/splatnet2statink/pull/70)
