### ISSUE TITLE
Filter for Salmon Run

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#379]
- [x] Stage
- [x] Special
- [x] <del>Title</del>
- [x] Cleared or not
- [x] Term
  - [x] Current
  - [x] Previous
  - [x] Version
  - [x] Term

Implementing "title" is difficult, because title (before) may unknown.  
<del>We can use Hazard Level for alternative. [see inkipedia](https://splatoonwiki.org/wiki/Salmon_Run_data#Quota_and_Hazard_Level)</del>
―― We can't use it. It should be hidden until a solution is found.

**Comment by frozenpandaman** [comment]
i'm working to implement title (before) now. but it seems `grade_point_delta` gets set to `20` when ranking up (title changes). and i don't know how ranking down works. so it might still not get set in some instances…
