### ISSUE TITLE
Development environment does not work (Recent version /v2.19)

### ISSUE THREAD

**Issue by niyari** [fetus-hina/stat.ink#382]
クライアント開発の為にローカルで検証できるよう、開発環境を構築していたところ、
> resources/app-link-logos

辺りのリソースが無いためエラーとなっているようです。
最近のバージョンで検証するための構成が変わっているのでしょうか。

**Comment by fetus-hina** [comment]
PHP 7.2 でないと動かない箇所があるとかはあるかもしれませんが（最近は開発が PHP 7.3 RC、運用が PHP 7.2 なので）、基本的には何も変わっていないはずです。
ただ、長らく１からの構築はやっていないので、もしかしたら「鍵が箱の中にある」ような状態ができあがってしまっているかもしれません。
後で検証してみます。

なお、resources/app-link-logos は Makefile の [このあたり](https://github.com/fetus-hina/stat.ink/blob/77ea37ba7cfdc8f737b2475760f0f07048ce8abe/Makefile#L431-L496) で自動的に作成されます。

もしかすると、現在、イカレコが Google Play で非公開になっているため、そこでエラーが発生しているのかもしれません。
もし ikarec 云々のエラーなのであれば、 Makefile の頭の方の `resources/.compiled/app-link-logos/ikarec-ja.png` の行を削除してみてください。
このファイルが存在しない場合、ナビゲーションバーのアイコンや手動登録フォーム部分のアイコンが出なくなりますが、それ以外は特に問題ないはずです。

**Comment by niyari** [comment]
[開発環境のセットアップ](https://github.com/fetus-hina/stat.ink/wiki/%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83%E3%81%AE%E3%82%BB%E3%83%83%E3%83%88%E3%82%A2%E3%83%83%E3%83%97) を行うと、 gearmand 等が抜けているため、 Dockerfile の yum install コマンドを併せて利用する必要があるようです。

手元の環境で Makefile を編集(現時点では動作する事を優先するため /app-link-logos の部分をすべてカット)し、2度目の make を行うと

>*** failed to apply m170804_103326_weapon2_bold (time: 0.013s)
0 from 239 migrations were applied.
Migration failed. The rest of the migrations are canceled.

となるようです。(このまま進めると Database Exception で落ちます。)

**Comment by niyari** [comment]
更新された [開発環境のセットアップ](https://github.com/fetus-hina/stat.ink/wiki/How-to-setup-a-development-environment) に従って構築する事ができました。
ご対応ありがとうございます。

**Comment by fetus-hina** [comment]
また何かありましたらお尋ねください
