### ISSUE TITLE
hope to add dark mode of stat.ink website

### ISSUE THREAD

**Issue by sakuyamaij** [fetus-hina/stat.ink#397]
With dark mode, we can
Improved Readability of Text
Better Contrast 
Reduced Eye Fatigue
Less Blue Light 
Can Save Small Amounts of Electric 
blabla...

**Comment by fetus-hina** [comment]
Basic support was added by #401.
It is not practical because it has not been adjusted.

Added Navbar "user" menu -> Color Scheme -> ****** Theme.

"Cyborg", "Darkly" and "Slate" are dark-mode theme.

See also: https://bootswatch.com/3/
