### ISSUE TITLE
Missing Timezones

### ISSUE THREAD

**Issue by guigas7** [fetus-hina/stat.ink#398]
I live in Brazil and the Timezone here is UTC-2 (in daylight saving time) and UTC-3. Did i just not find the option to select any UTC value or there isn't one?

**Comment by fetus-hina** [comment]
- I will add `UTC±hh:mm` values to "others" group.
- I want to add explicitly support for Latin American countries. However, I am short of knowledge of those countries. Is it possible to tell me which time zone I should prepare?

**Comment by fetus-hina** [comment]
Added `UTC+14`..`UTC-12` time zones. (No +30min/+45min etc. Because those time zones are [not supported by time zone database](http://php.net/manual/en/timezones.others.php).)

**Comment by fetus-hina** [comment]
Added Brazilian time zones, referred to Japanese/English Wikipedia and other time zone information websites.

Now, 6 time zones registered. Please let me know if there is a mistake or a better representation.

| IANA Identifier | Name |
|--|--|
| `America/Noronha` | Brazil (Fernando de Noronha) |
| `America/Sao_Paulo` | Brazil (Brasília) |
| `America/Fortaleza` | Brazil (Northeastern) |
| `America/Cuiaba` | Brazil (Mato Grosso) |
| `America/Manaus` | Brazil (Eastern Amazonas) |
| `America/Eirunepe` | Brazil (Weastern Amazonas) |

![image](https://user-images.githubusercontent.com/848666/52525494-f6bd8e80-2ced-11e9-9839-17ee48db6f8e.png)

**Comment by fetus-hina** [comment]
Closing this issue now.
If we have problems about South American time zones (of course, including Brazil), leave a comment to this issue below, or open a new issue.
