### ISSUE TITLE
0 kill の時の表示が ? になっている

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#4]
https://stat.ink/u/fetus_hina/70
![0kill](https://cloud.githubusercontent.com/assets/848666/10124125/f2f81076-6587-11e5-9293-5e657ba615bd.png)
![uyxsjkychre5jktbcn6vphubxq](https://cloud.githubusercontent.com/assets/848666/10124132/1377cada-6588-11e5-9b7d-f50a67574521.jpg)

たぶん表示だけだと思われるけどまだDB覗いていない

**Comment by fetus-hina** [comment]
```
 id | user_id | rule_id | map_id | weapon_id | level | rank_id | is_win | rank_in_team | kill | death |        start_at        |         end_at         | agent  | agent_versio
n |           at
----+---------+---------+--------+-----------+-------+---------+--------+--------------+------+-------+------------------------+------------------------+--------+-------------
--+------------------------
 70 |       1 |       1 |      7 |           |    21 |         | t      |            3 |      |     3 | 2015-09-28 02:11:08+09 | 2015-09-28 02:14:12+09 | IkaLog | 0.01
  | 2015-09-28 02:14:37+09
```

`INSERT` 時の問題っぽかった

**Comment by fetus-hina** [comment]
0k/7d の id=72 の送信ログを見ると `kill` が見当たらないので送信側っぽい
![72](https://cloud.githubusercontent.com/assets/848666/10124160/085cb696-6589-11e5-860f-8a9e85b55eb0.png)

**Comment by fetus-hina** [comment]
おそらく直ったようなので close。直ってなかったら reopen。

**Comment by mzsm** [comment]
https://stat.ink/u/mzsm/73

**Comment by mzsm** [comment]
<ikalog.outputs.statink.statink object at 0x063096D0> (enabled = True)
    {'agent': 'IkaLog',
     'agent_version': '0.01',
     'death': 0,
     'end_at': 1443377517,
     'image_result': '(PNG Data)',
     'kill': 5,
     'level': 39,
     'map': 'shionome',
     'my_point': 1031,
     'rank_in_team': 2,
     'result': 'win',
     'rule': 'nawabari',
     'start_at': 1443377332}

**Comment by fetus-hina** [comment]
つらい

**Comment by fetus-hina** [comment]
DBは相変わらず `NULL`
