### ISSUE TITLE
Add elapsed time for battles.

### ISSUE THREAD

**Issue by niyari** [fetus-hina/stat.ink#404]
ガチマッチやリーグマッチで延長したバトルを確認したいため、結果の一覧や詳細表示に試合時間を表示する項目が欲しいです。

**Comment by fetus-hina** [comment]
次の項目を一覧に追加しました。

- 試合時間
  - `5:00` のように表示します
- 試合時間（秒）
  - `300` のように表示します

詳細にも同様の追加をしています。

なお、延長したかどうかは勝敗表示部分に「KO」が表示されているか「時間」が表示されているかで判別でき（る場合があり）ます。
（クライアントアプリの送信データによってはこの部分が表示されない場合があります）
