### ISSUE TITLE
Change "gender" parameter optional (Splatfest Mode) : IkaLog l10n (en-NA)

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#43]
IkaLog Slack, l10n channel:
> three of the NA titles, "fiend", "defender" and "champion" apply to both genders, so you might not be able to do that

https://twitter.com/fetus_hina/status/684969551499415552

**Comment by frozenpandaman** [comment]
@fetus-hina Please note that the English title is "Fiend" not "Friend" (stat.ink says "Friend" currently, example [here](https://stat.ink/u/tyuryan/84298))

**Comment by fetus-hina** [comment]
Oh, Thanks

**Comment by frozenpandaman** [comment]
Happy to help!
