### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by frozenpandaman** [fetus-hina/stat.ink#47]
Had a look through `messages/ja/app.php` where there are a lot of corresponding English and Japanese sentences and phrases. I wanted to suggest some translations/phrasings for the English version of the site. Please see my suggested changes here:

https://gist.github.com/frozenpandaman/5b44ded588725094f576/revisions

In "Excluded: Posted Player, All Players(when Private Battle), Posted Player's Team Member(when Squad Battle or Splatfest Battle)", I wasn't sure what "posted player" meant, so I did not make any changes to that phrasing.

Sorry for not fixing these & just submitting a PR myself – not sure exactly what files besides just app.php I'd needed to have changed. Please let me know if I should do this or if you need anything else from me.

何か質問があれば、日本語もいいです。ありがとうございます！

**Comment by fetus-hina** [comment]
Thank you. I'll fix it.

**Comment by fetus-hina** [comment]
Could you get the meaning about "Posted Player" and sentense?
![exclude1](https://cloud.githubusercontent.com/assets/848666/12221897/3f708474-b7ef-11e5-93a8-f538afd1f8b2.png)
![exclude2](https://cloud.githubusercontent.com/assets/848666/12221899/43a3989c-b7ef-11e5-8203-ae70ede90b68.png)

**Comment by frozenpandaman** [comment]
That makes sense. Sorry for not understanding. I would say "uploader" (one who uploads/posts their battle to stat.ink). I think that captures the sense of "投稿者" but it is a tricky translation.

From your image I understand that in Private Battles, all players (blue) are excluded. In Squad Battles & Splatfest battles, uploader's teammates (orange) are excluded.

But data from the uploader ("posted player") is *always* excluded? Why?

Thanks for helping me understand!

**Comment by fetus-hina** [comment]
The sentence is used at this page: https://stat.ink/entire/weapons .
That page has a not translated string “※できる限り重複カウントしないように除外設定を行っていますが、連戦やナワバリフレンド合流の影響により重複カウントしやすい状況が発生します。”. This sentence may help make your sense.
I cannot translate this sentence. I try literal translation, “as much as possible / configured excluded for not duplicate count / there is possible to duplicate count / by continue(?) and(or?) join to friends.”

The stats page estimates global weapon usage.
I was setting it for "not duplicate count."


Private Battle:
Whole players ignored.
In this play, weapon data too-duplicate and players may playful(?).
It's a junk data for global weapon stats.


Squad Battle:
Teammates' data ignored.
In this play, teammates may fixed and weapons also fixed.


Splatfest:
Teammates' data ignored.
In this play, you can continue and teammate(s) also may so.


Others:
The uploader's data ignored.
The uploader's weapon always duplicate. It's not reflect global weapon usage.
(For example, if you choose "Carbon Roller" and play 3 battles, should the system count "Carbon Roller" 3 times? I think, no.)


Join Friends (Regular Battle):
The uploader's data ignored.
Friends' weapon maybe duplicate, but the system does not detect it now.

**Comment by frozenpandaman** [comment]
I think a translation of:
** This exclusion is in to attempt to minimize overcounting in weapon usage statistics.*
would be good. The second part of the sentence was a bit difficult for me to understand but I think it's saying "it is easy to overcount when playing multiple battles in a row with friends" or similar. However, probably just the first part is enough in attempt to justify why some data are excluded.

Thanks for your great explanation.

I agree Private Battles would provide junk weapon data. You are correct – people are more playful in Private Battles, or you could say they are less likely to take them seriously.

The rest makes sense to me as well, and is probably the best way to minimize overcounting/counting duplicates as much as possible.


Given all of that, I'd recommend these translations:

集計除外: プライベートマッチと、投稿ユーザ、タッグマッチ・フェスマッチ時の投稿者のチームメンバー  =>  Excluded: Private Battle data, uploader's data, teammates' data (during Squad Battles and Splatfest)

※できる限り重複カウントしないように除外設定を行っていますが、連戦やナワバリフレンド合流の影響により重複カウントしやすい状況が発生します。  =>  * This exclusion is in to attempt to minimize overcounting in weapon usage statistics.

Thanks again very much for spending so much time helping me understand!

**Comment by frozenpandaman** [comment]
@fetus-hina Just saw your translation of the first one: "*Excluded: The uploader, All players (Private Battle), Uploader\'s teammates (Squad Battle or Splatfest Battle)*"

That's clear to me and works as well!

**Comment by fetus-hina** [comment]
The website including your contribution has been released!
This issue close at this time. Please create another issue for new or update translation.

Thank you very much for all your help!
