### ISSUE TITLE
promodeler_mg と promodeler_rg の main_ref が正しくない

### ISSUE THREAD

**Issue by yukidaruma** [fetus-hina/stat.ink#505]
`promodeler_mg`, `promodeler_rg` について、`main_ref`が`promodeler_mg`であるべきところ、`promodeler_rg`になっています。
なお、`promodeler_pg`については正しく`promodeler_mg`が設定されています。

関係すると思われるコミット:
https://github.com/fetus-hina/stat.ink/blob/3eb9782b36e023fde6b9c4708629ce01922c3f83/migrations/m170720_202358_weapon2.php#L21-L22

[https://stat.ink/api/v2/weapon](https://stat.ink/api/v2/weapon) のレスポンス:

![1](https://user-images.githubusercontent.com/6897821/58392212-ebf7f100-8073-11e9-9518-0af8476423c0.png)

上記APIを利用した、整形済みデータ (ご参考用): ![fyi](https://user-images.githubusercontent.com/6897821/58392214-ebf7f100-8073-11e9-8cc4-33c34013f0a4.png)

**Comment by fetus-hina** [comment]
ご報告ありがとうございます。
データを修正し、デプロイしました。
