### ISSUE TITLE
ミステリーゾーンのステージ名が間違っている

### ISSUE THREAD

**Issue by wkoichi** [fetus-hina/stat.ink#522]
https://github.com/fetus-hina/stat.ink/blob/005c1a94e817b1e90368e5fcd79a7222f221c502/messages/ja/map2.php#L43

「ドジドジ」ではなく「トジトジ」です。

https://twitter.com/SplatoonJP/status/1140818267654651904

**Comment by fetus-hina** [comment]
ありがとうございます。修正します。
