### ISSUE TITLE
Can't type in fields in "Input new battle results"

### ISSUE THREAD

**Issue by frozenpandaman** [fetus-hina/stat.ink#535]
The following three text (numerical fields) can be selected, but not typed in:
![image](https://user-images.githubusercontent.com/7245874/61522302-f759ff80-a9c6-11e9-8e4c-61ed4c16e70f.png)
The only way to increment/decrement the numbers is by clicking the browser's stepper UI/arrows (for `<input type="number">` elements) on the side:
![image](https://user-images.githubusercontent.com/7245874/61522508-5a4b9680-a9c7-11e9-844c-66f6ab503fa1.png)

**Comment by fetus-hina** [comment]
Thank you for the report.
It looks someone stops key-press event... I'm checking JavaScript...

**Comment by fetus-hina** [comment]
This issue will be fixed in next deploy.

**Comment by fetus-hina** [comment]
Deployed new version including #534 and #535
