### ISSUE TITLE
統計（ブキ別）に指定外のフィルタが掛かる

### ISSUE THREAD

**Issue by niyari** [fetus-hina/stat.ink#591]
最近nバトルのみ指定した統計（ブキ別）ページの結果がデータなし、または一部の集計結果として表示されてしまうようです。
[統計（ブキ別）ページ](https://stat.ink/@fetus_hina/spl2/stat/by-weapon)
[統計（ブキ別）ページ(最近200バトル)](https://stat.ink/@fetus_hina/spl2/stat/by-weapon?filter%5Brule%5D=&filter%5Bmap%5D=&filter%5Brank%5D=&filter%5Bterm%5D=last-200-battles&filter%5Bterm_from%5D=&filter%5Bterm_to%5D=&filter%5Btimezone%5D=Asia%2FTokyo)

**Comment by fetus-hina** [comment]
ありがとうございます。調査します

**Comment by fetus-hina** [comment]
修正し、反映しました。 (v2.86.2)
報告ありがとうございました。
