### ISSUE TITLE
Color Scheme dropdown option leads to broken page

### ISSUE THREAD

**Issue by e-foley** [fetus-hina/stat.ink#612]
When I click my name in the menu to produce a dropdown menu and then click Color Scheme, I get taken to a broken page. The URL shown in the header is `javascript:jQuery('#color-scheme-dialog').modal()`. The page itself only contains the text `[object Object]`.

I encounter this issue when using Firefox 70.0.1.

**Comment by fetus-hina** [comment]
Thank you reporting this issue. I've verified this issue.

**Comment by fetus-hina** [comment]
Maybe fixed it now.
