### ISSUE TITLE
シンプルリスト表示が意図した表示にならない

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#66]
https://twitter.com/taro22_manmenmi/status/696275661510414336
少なくとも iOS Safari でシンプル表示を行った時に幅が充分確保されていなくて省略表示が意図したものより早く出ている

**Comment by fetus-hina** [comment]
iOS端末が手元にないのでわからない

**Comment by deathmetalland** [comment]
iOSでのスクリーンショットを添付します。
ステージとバトルのところが右に余白があるのに省略表示が始まっている点を指していそうです。

![screen shot 2016-03-10 at 23 09 15](https://cloud.githubusercontent.com/assets/1370852/13671768/3a6ad8d0-e715-11e5-95f8-2f3aa35c5c87.png)

**Comment by fetus-hina** [comment]
はい、その通りです。
幅が足りなくなると「…」になること自体は想定通りの動きですが、日付部分が幅として奪われてしまっているというのが問題点です。

**Comment by fetus-hina** [comment]
URBANO L02 (Android 4.2) の標準ブラウザで再現する感

**Comment by fetus-hina** [comment]
https://twitter.com/kichi_robo/status/729361019902959616 大丈夫っぽい
