### ISSUE TITLE
Different rounding between current X power and peak X power on splat log

### ISSUE THREAD

**Issue by e-foley** [fetus-hina/stat.ink#697]
![image](https://user-images.githubusercontent.com/6338134/83240013-9f933580-a14d-11ea-982a-851bc75475ab.png)

This appears to be a tiny bug: in [my splat log](https://stat.ink/@syzygy/spl2), my current Clam Blitz power displays as **2,012.7**, but my peak Clam Blitz power displays as **2,012.0**. It looks like all of the "peak" ratings are rounded down.

**Comment by fetus-hina** [comment]
Sorry for inconvenience.
It probably forgot to reflect the data after last battle.
I'm thinking of trying to fix it.
Perhaps if you play Clam Blitz (in Solo Queue) again, you'll get the correct stats. (You don't have to wait for the fix.)

**Comment by fetus-hina** [comment]
Sorry, you're right.
I found a bug that truncates(floor) the number after geting the maximum value of X-power.
It'll fix soon.
