### ISSUE TITLE
草生やす

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#75]
https://twitter.com/mzyy94/status/703168676237697024

**Comment by fetus-hina** [comment]
- [ ] 草生やすライブラリがあるとうれしい（この程度すぐ実装できるけども）
- [ ] どこに生やすのさ

**Comment by mzyy94** [comment]
https://github.com/gammasoft/calendar

**Comment by fetus-hina** [comment]
@mzyy94 :seedling::seedling::seedling::seedling::seedling::seedling::seedling::seedling::seedling::seedling:

**Comment by mzyy94** [comment]
@fetus-hina  :four_leaf_clover: : :four_leaf_clover:  :four_leaf_clover: : :four_leaf_clover: :four_leaf_clover: : :four_leaf_clover:

**Comment by mzyy94** [comment]
どこに生やすか
プロフィールページ(/u/mzyy94)のレイアウト変える必要が出てきそう

**Comment by deathmetalland** [comment]
:+1:

**Comment by mzyy94** [comment]
https://github.com/wa0x6e/cal-heatmap

**Comment by mzyy94** [comment]
こっちのほうがメンテされてて良さそう

https://github.com/Kraigo/glanceyear

**Comment by fetus-hina** [comment]
glanceyear は、bower対応なし、release tagなし、2014年で微妙っぽ

**Comment by mzyy94** [comment]
現実は厳しい

**Comment by fetus-hina** [comment]
gammasoft/calendar はなんか色々微妙感あるので他のも試してみる :seedling:

**Comment by mzyy94** [comment]
wa0x6e/cal-heatmap ドキュメントは優秀

**Comment by mzyy94** [comment]
![2016-02-28 15 46 16](https://cloud.githubusercontent.com/assets/2971112/13377935/1cd64848-de34-11e5-9a03-789ba748d467.png)

※画像はイメージです。
