### ISSUE TITLE
日報のプレイヤー名が{name}になっている

### ISSUE THREAD

**Issue by wkoichi** [fetus-hina/stat.ink#781]
日報を表示したところ、プレイヤー名が{name}のままになっています。
https://stat.ink/@wkoichi/spl2/stat/report/2020/10

<img width="450" alt="stat_ink___こいちさんのバトルレポート" src="https://user-images.githubusercontent.com/387175/97061440-d91f7e00-15d1-11eb-9594-e6e5ff07129d.png">

**Comment by fetus-hina** [comment]
ありがとうございます。
修正しました。
