### ISSUE TITLE
IkaLog が送信してきている追加パラメータに対応する

### ISSUE THREAD

**Issue by fetus-hina** [fetus-hina/stat.ink#8]
* `rank_exp`
* `rank_after`
* `rank_exp_after`
* `cash_after`

かな

**Comment by hasegaw** [comment]
いまのところそれぐらいですね。（また増やすかもしれませんが）

**Comment by hasegaw** [comment]
追加。
- knock_out ("yes" or "no")を送信していますが認識していないようです。
- death_reason というmap(hash)を追加送信するようになりました（まだ画像認識の精度がひくいですが。)
{ 殺されたブキID: 回数, 殺されたブキID: 回数, 殺されたブキID: 回数, ... } です。
ブキID は weapon と同じですがホコショット、ガチホコの爆発、ガチホコ窒息、
サブウエポン、スペシャルウエポンは別途追加定義しないといけないのでまたお知らせします。

{'agent': 'IkaLog',
 'agent_version': 'unknown',
 'death': 8,
 'death_reasons': {'dualsweeper': 1, 'nova': 3, 'sshooter': 3},
 'end_at': 1444209710,
 'image_judge': '(PNG Data)',
 'image_result': '(PNG Data)',
 'kill': 6,
 'knock_out': 'no',
 'level': 49,
 'map': 'tachiuo',
 'rank': 'a+',
 'rank_after': 'a+',
 'rank_exp': 50,
 'rank_exp_after': 60,
 'rank_in_team': 4,
 'result': 'win',
 'rule': 'hoko',
 'start_at': 1444209409,
 'weapon': 'dualsweeper_custom'}

**Comment by fetus-hina** [comment]
`rank_exp`, `rank_after`, `rank_exp_after`, `level_after` `cash`, `cash_after` を追加しました。
（整合性面で追加しておいた方がよさそうなのも増えています）

また、`knock_out` が壊れている問題も修正しました。
https://github.com/fetus-hina/stat.ink/commit/b89b81e92f12ec80d31200e89cc073e2f344c0c9#diff-f3d5a624f7d006e73e9277848b000d1cR212 つらい。

**Comment by fetus-hina** [comment]
サブウェポンは https://github.com/fetus-hina/stat.ink/blob/master/migrations/m150928_122509_subweapon.php#L16
スペシャルは https://github.com/fetus-hina/stat.ink/blob/master/migrations/m150929_064010_special.php#L16
と整合がとれているとうれしいです（それぞれ左側が内部の `key` です）
バリアとかスーパーセンサーは絶対他のイカを kill はしませんが…。

あとは、とりあえず実装するために仮に次の値で定義しています。

* `unknown` : 不明
* `oob` : 場外で死亡（転落・水死の判定がつかない場合）
* `drawn`: 水死
* `fall` : 転落死
* `hoko_shot` : ホコショット
* `hoko_barrier` : ホコバリア爆発で死亡
* `hoko_inksplode` : ホコ保持時間で死亡（"The Rainmaker Inksploded" らしいので）

**Comment by hasegaw** [comment]
ありがとうございます。

現状 unknown を送信するコードは想定していない（死因が確定できるものだけ送信）ですが今後使うかもしれません。

水死／転落死が区別できるか検討して、ダメそうなら oob を使うようにします。

**Comment by apricot385** [comment]
割合は極低と思いますが、

ガチホコの
バリアでやられた！

（敵の爆破時でも時間切れ自滅でもなく、爆破前バリア接触ダメージでの致死）は
実装予定ありますでしょうか？

**Comment by hasegaw** [comment]
可能ですが現状学習に必要なスクリーンショットが確保できていません。

**Comment by fetus-hina** [comment]
たぶん key 分けたほうがいいですよねえ。さて名前どうしよう…

**Comment by hasegaw** [comment]
ごくまれにしか出ない奴はプライベートゲームで発生させてスクリーンショットとるしかないかな。。。

**Comment by apricot385** [comment]
今回に限ってはさんぽできる時間帯なら一人でも撮れそうです(最速10/8 3:00～)

**Comment by hasegaw** [comment]
death_reasons = {} という状態で death_reasons should be a map エラーが帰ってくるようです。
(空っぽが未定義かどうかって話はありますが。)

こちら側の msgpack 実装は要素ゼロのマップを正しく返しているようですが、
stat.ink 側でコレを受けられるようにはできそうですか？
````
Python 3.4.3 (default, Jul 13 2015, 12:18:23)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import umsgpack
>>> umsgpack.packb({})
b'\x80'
>>> umsgpack.packb({'a':'b'})
b'\x81\xa1a\xa1b'
>>>
````

**Comment by fetus-hina** [comment]
たぶん直ったと思います

**Comment by hasegaw** [comment]
空mapの件了解です。（こちらも送らないようにしてしまいましたが、今後なにがあるかも判らないので。。。）

**Comment by hasegaw** [comment]
このチケットに書かれている stat.ink 側での対応は一通り終わっていると思います。
今後の追加項目は別チケットにしましょう。
