### ISSUE TITLE
Reset password / Recover profile

### ISSUE THREAD

**Issue by Brazoli** [fetus-hina/stat.ink#844]
I'm having trouble accessing my account, is it possible to reset the password and recover my profile?

**Comment by fetus-hina** [comment]
- If you have configured your email address to your profile:
  - Send an email from that email address with the information below (to `hina@bouhime.com`):
    - Log in name ( `@foo` in your public profile page's URL)
    - The first 8 characters of your API Token.
    - Hashed password (The generation method is described at the bottom of the page.)
- If you have NOT configured your email address to your profile:
  - Send an email (to `hina@bouhime.com`) or send a Direct Message on Twitter ([`@fetus_hina`](https://twitter.com/fetus_hina)) with the information below:
    - Log in name ( `@foo` in your public profile page's URL)
    - The first 8 characters of your API Token.
    - Hashed password (The generation method is described at the bottom of the page.)
- If you lost your Log in name or API Token
  - Unfortunately, there's no way to recover it.

## How to generate a "hashed password"

- If you can use some programming language:
  - If the environment supports "Argon2i" or "Argon2id":
    - Generate hashed password with Argon2i or Argon2id.
      Example in PHP (7.3 or later, if you use PHP 7.2 you can use `PASSWORD_ARGON2I`): (`new_password` should be replaced with your password)
      ```php
      <?php

      printf("%s\n", password_hash('new_password', PASSWORD_ARGON2ID));
      ```
      It will be generated like this:
      ```
      $argon2id$v=19$m=65536,t=4,p=1$hWRHMvFjYc3lSIbBG0B46g$pCSUP7FwG0GzzVgjR4iXHfazL36rCNWRf1jRw0i0PSY
      ```
  - If the environment supports "Bcrypt":
    - Generate hashed password with Bcrypt with pre-processed password: (pseudo-code)
      ```
      password := 'new_password'

      hash_binary := sha256_binary( password )
      b64_string := base64_encode( hash_binary )
      b64_string_trimmed := trim_right( b64_string, '=' ) // remove padding on the right side (===)
      preprocessed := substring( b64_string_trimmed + ":" + password, 0, 72 )

      hashed_password := bcrypt( preprocessed )
      ```
      [The preprocess method in our real code](https://github.com/fetus-hina/stat.ink/blob/5124d59ed1047ee0912612c732e4699a27675b34/components/helpers/Password.php#L42-L50).
      Debugging information (the `preprocessed` value when input `new_password` as a password):
      ```
      ALnmYiMXovtijVUUuGbU58UrWxSQJ4JWRa4/1ygn6E4:new_password
      ```
      And finally generated like this:
      ```
      $2y$10$MGblEME4BnG4/0bOPESPLOj3WF36pFvKmVBZFECSdHzF1.VKHOeS2
      ```
      Note 1: The `$2y$` part may be one of the following, depending on the environment in which it is generated: `$2$`, `$2a$`, ` $2b$`, `$2x$` or `$2y$`.
      Note 2: The `$10$` part can be any number between `$04$` and `$31$`.
  - If you haven't:
    - Open https://wandbox.fetus.jp/permlink/i4FZTVIqkxgVTw3h
    - Edit password on the code and click "Run" button
    - The hashed password will be displayed in the black box at the bottom
      Note 1: `wandbox.fetus.jp` is one of my website.
      Note 2: Do NOT click "Share This Code" button after edit the code. Your password will be stored in my server INDEFINITELY.
