### ISSUE TITLE
Seemingly no way to delete an account

### ISSUE THREAD

**Issue by LimeInkling** [fetus-hina/stat.ink#853]
I have been thinking of deleting one of my accounts, but I have looked all around the site, and there does not seem to be an option to do so. It's weird, because I remember this option being there in the past.

**Comment by fetus-hina** [comment]
Yes, at this time, we do not provide a way to delete your account(s).

Also, we have never implemented the feature in the past.

**Comment by LimeInkling** [comment]
I apologise for not closing the issue earlier. Thanks for the assistance.
