### ISSUE TITLE
Stats (Splatfest - Normal or Pro) Pages

### ISSUE THREAD

**Issue by niyari** [fetus-hina/stat.ink#870]
フェスパワーの推移をグラフで確認できるよう、統計ページの分類にフェス(レギュラー)、フェス(チャレンジ)を追加することは可能でしょうか。

現在は、検索にて絞り込みを行い[バトルの詳細ページ](https://stat.ink/@fetus_hina/spl2/3426350)で直近のパワー等が確認できますが、[ナワバリバトル統計ページ](https://stat.ink/@fetus_hina/spl2/stat/nawabari)以外にも、フェスを1つのルールとしてフェスパワー等を確認したいです。

**Comment by fetus-hina** [comment]
[フェスパワー統計ページ](https://stat.ink/@fetus_hina/spl2/stat/splatfest)を作成しました
