### ISSUE TITLE
user-statsが更新されていない

### ISSUE THREAD

**Issue by wkoichi** [fetus-hina/stat.ink#890]
ここ10日ほどuser-statsの内容が更新されていないようです。
何人か見てみましたが、皆さんupdated_atが2021-02-11でした。

https://stat.ink/api/v2/user-stats?screen_name=wkoichi
```
{
    "updated_at": {
        "time": 1613074083,
        "iso8601": "2021-02-11T20:08:03+00:00"
    },
```

**Comment by fetus-hina** [comment]
タスクランナーを再起動したので更新されたと思います

**Comment by wkoichi** [comment]
更新されていました。ありがとうございます。
