### ISSUE TITLE
Detailed Export

### ISSUE THREAD

**Issue by niyari** [fetus-hina/stat.ink#932]
スプラトゥーン2 プレイ配信時に、統計情報やグラフ、過去のマッチング履歴等を表示させるため、データのエクスポート機能があるとありがたいです。
見たい機能はstat.inkに揃っているのですが、すぐに欲しいデータの表示がページをまたいでいたり、1バトル毎にポチポチ操作して負荷をかけるのも申し訳ないかな、と気持ちがあります。

ローカルに立てたstat.inkレプリカにインポートすれば同じように表示されるデータであると一番うれしいですが、非常に重い処理と認識しているため、1か月に1回などの上限があるものでも良いと思います。

**Comment by fetus-hina** [comment]
stat.ink の表示を再現するにはほぼ全てのデータをエクスポート・インポートしないといけないため、現実的ではありません。

必要なデータを提供するAPIの整備等の方が妥当性が高いと思いますので、必要なものを列挙いただければと思います。
